-------------------------------------------------------------------------------
-- SQL Script generated by FormSync 9.1.0.9 As of 19/11/2014 05:01 p.m.
-- Source Configuration: BAR_Forms
-- Objects Scripted:
--   Strings: sZWM_ItemCollectBox, sZWM_MinQty, sZWM_ReorderQty, sZWM_ReorderUM,
--      sZWM_RsvdFixed
-------------------------------------------------------------------------------
DECLARE @FormID int
DELETE FROM [Strings] WHERE [Name] = N'sZWM_ItemCollectBox' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 

INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sZWM_ItemCollectBox', N'Art' + NCHAR(237) + N'culos de Caja Recolectora', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sZWM_MinQty' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 

INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sZWM_MinQty', N'Minimun Qty', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sZWM_ReorderQty' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 

INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sZWM_ReorderQty', N'Reorder Qty', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sZWM_ReorderUM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 

INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sZWM_ReorderUM', N'Reorder UM', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sZWM_RsvdFixed' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 

INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sZWM_RsvdFixed', N'Reserva Fija', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'fZWM_CollectBoxMoveTransactions' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 

INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'fZWM_CollectBoxMoveTransactions', N'Transacciones de Movimiento de Caja Recolectora', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'fZWM_DeleteTempReservUtility' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 

INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'fZWM_DeleteTempReservUtility', N'Utiler' + NCHAR(237) + N'a para borrar Reserva temporal', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'oZWM_MvTrans' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 

INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'oZWM_MvTrans', N'Transacciones de Movimiento de Caja Recolectora', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sZWM_MinQty' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 

INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sZWM_MinQty', N'Minimun Qty', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sZWM_MinUM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 

INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sZWM_MinUM', N'Min. UM', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sZWM_ReorderQty' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 

INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sZWM_ReorderQty', N'Reorder Qty', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sZWM_ReorderUM' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 

INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sZWM_ReorderUM', N'Reorder UM', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sZWM_RsvdFixed' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 

INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sZWM_RsvdFixed', N'Reserva Fija', NULL, NULL, 1, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'fCollectBoxSupplyReport' AND [ScopeType] = 1 AND [ScopeName] = N'[NULL]' 

INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'fCollectBoxSupplyReport', N'Collect Box Supply Report', NULL, NULL, 1, N'[NULL]', NULL)

