-------------------------------------------------------------------------------
-- SQL Script generated by FormSync 9.1.0.9 As of 10/10/2014 05:04 p.m.
-- Source Configuration: BAR_Forms
-- Objects Scripted:
--   Strings: fZWM_FreightByWeights, fZWM_Routes, fZWM_ZipAddress, fZWM_Zips,
--      oZWM_FreightWeights, oZWM_Routes, oZWM_ZipAddrs, oZWM_Zips,
--      sZWM_Distance, sZWM_FreightAmount, sZWM_FreightMinAmount, sZWM_Route,
--      sZWM_ShipViaMode=C, sZWM_ShipViaMode=F, sZWM_ZipAddrEnding,
--      sZWM_ZipAddrEndingNum, sZWM_ZipAddrStarting, sZWM_ZipAddrStartingNum
-------------------------------------------------------------------------------
DECLARE @FormID int
DELETE FROM [Strings] WHERE [Name] = N'fZWM_FreightByWeights' AND [ScopeType] = 0  AND [ScopeName] = N'[NULL]' 

INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'fZWM_FreightByWeights', N'Flete por Peso y Distancia', NULL, NULL, 0, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'fZWM_Routes' AND [ScopeType] = 0  AND [ScopeName] = N'[NULL]' 

INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'fZWM_Routes', N'Rutas', NULL, NULL, 0, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'fZWM_ZipAddress' AND [ScopeType] = 0  AND [ScopeName] = N'[NULL]' 

INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'fZWM_ZipAddress', N'Direcciones por C' + NCHAR(243) + N'digo Postal', NULL, NULL, 0, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'fZWM_Zips' AND [ScopeType] = 0  AND [ScopeName] = N'[NULL]' 

INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'fZWM_Zips', N'C' + NCHAR(243) + N'digos Postales', NULL, NULL, 0, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'oZWM_FreightWeights' AND [ScopeType] = 0  AND [ScopeName] = N'[NULL]' 

INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'oZWM_FreightWeights', N'Fletes por Peso', NULL, NULL, 0, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'oZWM_Routes' AND [ScopeType] = 0  AND [ScopeName] = N'[NULL]' 

INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'oZWM_Routes', N'Rutas', NULL, NULL, 0, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'oZWM_ZipAddrs' AND [ScopeType] = 0  AND [ScopeName] = N'[NULL]' 

INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'oZWM_ZipAddrs', N'Direcciones por C' + NCHAR(243) + N'digo Postal', NULL, NULL, 0, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'oZWM_Zips' AND [ScopeType] = 0  AND [ScopeName] = N'[NULL]' 

INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'oZWM_Zips', N'C' + NCHAR(243) + N'digos Postales', NULL, NULL, 0, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sZWM_Distance' AND [ScopeType] = 0  AND [ScopeName] = N'[NULL]' 

INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sZWM_Distance', N'Distancia', NULL, NULL, 0, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sZWM_FreightAmount' AND [ScopeType] = 0  AND [ScopeName] = N'[NULL]' 

INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sZWM_FreightAmount', N'Monto Flete', NULL, NULL, 0, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sZWM_FreightMinAmount' AND [ScopeType] = 0  AND [ScopeName] = N'[NULL]' 

INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sZWM_FreightMinAmount', N'Flete Valor m' + NCHAR(237) + N'nimo', NULL, NULL, 0, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sZWM_Route' AND [ScopeType] = 0  AND [ScopeName] = N'[NULL]' 

INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sZWM_Route', N'Ruta', NULL, NULL, 0, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sZWM_ShipViaMode=C' AND [ScopeType] = 0  AND [ScopeName] = N'[NULL]' 

INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sZWM_ShipViaMode=C', N'Cliente Retira', NULL, NULL, 0, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sZWM_ShipViaMode=F' AND [ScopeType] = 0  AND [ScopeName] = N'[NULL]' 

INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sZWM_ShipViaMode=F', N'Flete con Cargo', NULL, NULL, 0, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sZWM_ZipAddrEnding' AND [ScopeType] = 0  AND [ScopeName] = N'[NULL]' 

INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sZWM_ZipAddrEnding', N'Altura Final', NULL, NULL, 0, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sZWM_ZipAddrEndingNum' AND [ScopeType] = 0  AND [ScopeName] = N'[NULL]' 

INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sZWM_ZipAddrEndingNum', N'Altura Final', NULL, NULL, 0, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sZWM_ZipAddrStarting' AND [ScopeType] = 0  AND [ScopeName] = N'[NULL]' 

INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sZWM_ZipAddrStarting', N'Altura Inicial', NULL, NULL, 0, N'[NULL]', NULL)
-------------------------------------------------------------------------------
DELETE FROM [Strings] WHERE [Name] = N'sZWM_ZipAddrStartingNum' AND [ScopeType] = 0  AND [ScopeName] = N'[NULL]' 

INSERT INTO [Strings] ([Name], [String], [String2], [String3], [ScopeType], [ScopeName], [LockedBy] ) 
VALUES (N'sZWM_ZipAddrStartingNum', N'Altura Inicial', NULL, NULL, 0, N'[NULL]', NULL)
-------------------------------------------------------------------------------
