/****** Object:  StoredProcedure [dbo].[NextGrnSp]    Script Date: 01/15/2015 12:21:27 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[NextGrnSp]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[NextGrnSp]
GO

/****** Object:  StoredProcedure [dbo].[NextGrnSp]    Script Date: 01/15/2015 12:21:27 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

--  Converted from next-est.p

/* $Header: /ApplicationDB/Stored Procedures/NextEstSp.sp 9     3/04/10 3:18p Dahn $ */
/*
***************************************************************
*                                                             *
*                           NOTICE                            *
*                                                             *
*   THIS SOFTWARE IS THE PROPERTY OF AND CONTAINS             *
*   CONFIDENTIAL INFORMATION OF INFOR AND/OR ITS AFFILIATES   *
*   OR SUBSIDIARIES AND SHALL NOT BE DISCLOSED WITHOUT PRIOR  *
*   WRITTEN PERMISSION. LICENSED CUSTOMERS MAY COPY AND       *
*   ADAPT THIS SOFTWARE FOR THEIR OWN USE IN ACCORDANCE WITH  *
*   THE TERMS OF THEIR SOFTWARE LICENSE AGREEMENT.            *
*   ALL OTHER RIGHTS RESERVED.                                *
*                                                             *
*   (c) COPYRIGHT 2010 INFOR.  ALL RIGHTS RESERVED.           *
*   THE WORD AND DESIGN MARKS SET FORTH HEREIN ARE            *
*   TRADEMARKS AND/OR REGISTERED TRADEMARKS OF INFOR          *
*   AND/OR ITS AFFILIATES AND SUBSIDIARIES. ALL RIGHTS        *
*   RESERVED.  ALL OTHER TRADEMARKS LISTED HEREIN ARE         *
*   THE PROPERTY OF THEIR RESPECTIVE OWNERS.                  *
*                                                             *
*************************************************************** 
*/
/* $Archive: /ApplicationDB/Stored Procedures/NextEstSp.sp $
 *
 * SL8.02 9 rs4588 Dahn Thu Mar 04 15:18:04 2010
 * rs4588 copyright header changes
 *
 * SL8.01 8 rs3953 Vlitmano Tue Aug 26 17:08:28 2008
 * RS3953 - Changed a Copyright header?
 *
 * SL8.01 7 rs3953 Vlitmano Mon Aug 18 15:30:04 2008
 * Changed a Copyright header information(RS3959)
 *
 * SL8.00 6 RS2968 nkaleel Fri Feb 23 04:07:02 2007
 * changing copyright information(RS2968)
 *
 * SL8.00 5 RS2968 prahaladarao.hs Tue Jul 11 10:10:30 2006
 * RS 2968, Name change CopyRight Update.
 *
 * SL7.05 4 91818 NThurn Fri Jan 06 16:20:05 2006
 * Inserted standard External Touch Point call.  (RS3177)
 *
 * $NoKeywords: $
 */
CREATE PROCEDURE [dbo].[NextGrnSp] (
  @Context   LongList
, @Prefix    GrnPrefixType
, @KeyLength INT
, @Key       LongList OUTPUT
, @Infobar   Infobar  OUTPUT
)
AS

   -- Check for existence of Generic External Touch Point routine (this section was generated by SpETPCodeSp and inserted by CallETPs.exe):
   IF OBJECT_ID(N'dbo.EXTGEN_NextGrnSp') IS NOT NULL
   BEGIN
      DECLARE @EXTGEN_SpName sysname
      SET @EXTGEN_SpName = N'dbo.EXTGEN_NextGrnSp'
      -- Invoke the ETP routine, passing in (and out) this routine's parameters:
      DECLARE @EXTGEN_Severity int
      EXEC @EXTGEN_Severity = @EXTGEN_SpName
         @Context
         , @Prefix
         , @KeyLength
         , @Key OUTPUT
         , @Infobar OUTPUT
 
      -- ETP routine can RETURN 1 to signal that the remainder of this standard routine should now proceed:
      IF @EXTGEN_Severity <> 1
         RETURN @EXTGEN_Severity
   END
   -- End of Generic External Touch Point code.
 
DECLARE
  @Severity INT
SET @Infobar = NULL

EXEC @Severity = SetNextKeySp
  @TableName  = 'grn_hdr'
, @ColumnName = 'grn_num'
, @Prefix     = @Prefix
, @KeyLength  = @KeyLength
, @Type       = 'EST'
, @KeyStr     = @Key OUTPUT
, @Infobar    = @Infobar OUTPUT

RETURN @Severity
GO


