/****** Object:  StoredProcedure [dbo].[ZWM_ItemStorageReportSp]    Script Date: 01/09/2015 14:45:58 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ZWM_ItemStorageReportSp]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[ZWM_ItemStorageReportSp]
GO

/****** Object:  StoredProcedure [dbo].[ZWM_ItemStorageReportSp]    Script Date: 01/09/2015 14:45:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[ZWM_ItemStorageReportSp]( 
	@POStart			PoNumType = NULL
	,@POEnd				PoNumType = NULL
	,@GRNStart			GrnNumType = NULL
	,@GRNEnd			GrnNumType = NULL
	,@ItemStart			ItemType = NULL
	,@ItemEnd			ItemType = NULL
	,@CtrlUMStock1		FlagNyType = 0
	,@CtrlDimStock1		FlagNyType = 0
	,@CtrlUMStock2		FlagNyType = 0
	,@CtrlDimStock2		FlagNyType = 0
	,@CtrlWeight		FlagNyType = 0
	,@CtrlBarCode		FlagNyType = 0
	,@CtrlSeqStor		FlagNyType = 0
	,@CtrlVolWeight		FlagNyType = 0
)
AS

-- Check for existence of Generic External Touch Point routine (this section was generated by SpETPCodeSp and inserted by CallETPs.exe):
   IF OBJECT_ID(N'dbo.EXTGEN_ZWM_ItemStorageReportSp') IS NOT NULL
   BEGIN
      DECLARE @EXTGEN_SpName sysname
      SET @EXTGEN_SpName = N'dbo.EXTGEN_ZWM_ItemStorageReportSp'
      -- Invoke the ETP routine, passing in (and out) this routine's parameters:
      DECLARE @EXTGEN_Severity int
      EXEC @EXTGEN_Severity = @EXTGEN_SpName
		@POStart
		,@POEnd
		,@GRNStart
		,@GRNEnd
		,@ItemStart
		,@ItemEnd
		,@CtrlUMStock1
		,@CtrlDimStock1
		,@CtrlUMStock2
		,@CtrlDimStock2
		,@CtrlWeight
		,@CtrlBarCode
		,@CtrlSeqStor
		,@CtrlVolWeight
		
       -- ETP routine can RETURN 1 to signal that the remainder of this standard routine should now proceed:
      IF @EXTGEN_Severity <> 1
         RETURN @EXTGEN_Severity
   END
   -- End of Generic External Touch Point code.
   
   
   CREATE TABLE #tempTable
   (Articulo nvarchar(30), UMStock1 nvarchar(3), AnchoStk1 decimal(11,3), AltoStk1 decimal(11,3), ProfStk1 decimal(11,3),UMStock2 nvarchar(3), AnchoStk2 decimal(11,3), AltoStk2 decimal(11,3), ProfStk2 decimal(11,3), Peso decimal(11,5), CodBar nvarchar(40), PesoAfor decimal(9,2),Ranking tinyint, AtributLote nvarchar(25))
   
   
   ------------------------------------------------------------------------------------------------- PURCHASE ORDER
   
   IF @POStart is not null OR @POEnd is not null
   BEGIN
   		SET @POStart = ISNULL(dbo.ExpandKyByType('PoNumType', @POStart), dbo.LowString('PoNumType'))   
		SET @POEnd = ISNULL(dbo.ExpandKyByType('PoNumType', @POEnd), dbo.LowString('PoNumType'))  
		
		INSERT INTO #tempTable 
		(Articulo,UMStock1,AnchoStk1,AltoStk1,ProfStk1,UMStock2,AnchoStk2,AltoStk2,ProfStk2,Peso,CodBar,PesoAfor,Ranking,AtributLote)
		SELECT distinct(i.item),i.ZWM_UMStock1,i.ZWM_Stk1Width,i.ZWM_Stk1Height,i.ZWM_Stk1Depth,i.ZWM_UMStock2,i.ZWM_Stk2Width,i.ZWM_Stk2Height,i.ZWM_Stk2Depth,i.unit_weight ,i.ZWM_BarCode,i.ZWM_VolumetricWeight,
		iw.ranking,i.lot_attr_group
		FROM item i
		INNER JOIN zwm_itm_whse iw
		ON i.item = iw.item
		INNER JOIN poitem poi
		ON i.item = poi.item
		WHERE poi.po_num BETWEEN @POStart AND @POEnd
		AND(
		(i.ZWM_UMStock1 IS NULL AND @CtrlUMStock1 = 1)
		OR (i.ZWM_Stk1Width IS NULL OR i.ZWM_Stk1Height IS NULL OR i.ZWM_Stk1Depth IS NULL AND @CtrlDimStock1 = 1)
		OR (i.ZWM_UMStock2 IS NULL AND @CtrlUMStock2 = 1)
		OR (i.ZWM_Stk2Width IS NULL OR i.ZWM_Stk2Height IS NULL OR i.ZWM_Stk2Depth IS NULL AND @CtrlDimStock2 = 1)
		OR (i.unit_weight IS NULL OR i.unit_weight=0 AND @CtrlWeight = 1)
		OR (i.ZWM_BarCode IS NULL AND @CtrlBarCode = 1)
		OR (iw.ranking IS NULL AND @CtrlSeqStor = 1)
		OR (i.ZWM_VolumetricWeight IS NULL AND @CtrlVolWeight = 1)
		OR (i.lot_attr_group)IS NOT NULL)
		
   END
   ------------------------------------------------------------------------------------------------- /PURCHASE ORDER
   
   ------------------------------------------------------------------------------------------------- GRN
   IF @GRNStart is not null OR @GRNEnd is not null
   BEGIN
		SET @GRNStart = ISNULL(dbo.ExpandKyByType('GrnNumType', @GRNStart), dbo.LowString('GrnNumType'))   
		SET @GRNEnd = ISNULL(dbo.ExpandKyByType('GrnNumType', @GRNEnd), dbo.LowString('GrnNumType')) 
		
		INSERT INTO #tempTable 
		(Articulo,UMStock1,AnchoStk1,AltoStk1,ProfStk1,UMStock2,AnchoStk2,AltoStk2,ProfStk2,Peso,CodBar,PesoAfor,Ranking,AtributLote)
		SELECT distinct(i.item),i.ZWM_UMStock1,i.ZWM_Stk1Width,i.ZWM_Stk1Height,i.ZWM_Stk1Depth,i.ZWM_UMStock2,i.ZWM_Stk2Width,i.ZWM_Stk2Height,i.ZWM_Stk2Depth,i.unit_weight,i.ZWM_BarCode,i.ZWM_VolumetricWeight,
		iw.ranking,i.lot_attr_group
		FROM item i
		INNER JOIN zwm_itm_whse iw
		ON i.item = iw.item
		INNER JOIN poitem poi
		ON i.item = poi.item
		INNER JOIN grn_line grn
		ON grn.po_num = poi.po_num
		WHERE poi.po_num BETWEEN @GRNStart AND @GRNEnd
		AND(
		(i.ZWM_UMStock1 IS NULL AND @CtrlUMStock1 = 1)
		OR (i.ZWM_Stk1Width IS NULL OR i.ZWM_Stk1Height IS NULL OR i.ZWM_Stk1Depth IS NULL AND @CtrlDimStock1 = 1)
		OR (i.ZWM_UMStock2 IS NULL AND @CtrlUMStock2 = 1)
		OR (i.ZWM_Stk2Width IS NULL OR i.ZWM_Stk2Height IS NULL OR i.ZWM_Stk2Depth IS NULL AND @CtrlDimStock2 = 1)
		OR (i.unit_weight IS NULL OR i.unit_weight=0 AND @CtrlWeight = 1)
		OR (i.ZWM_BarCode IS NULL AND @CtrlBarCode = 1)
		OR (iw.ranking IS NULL AND @CtrlSeqStor = 1)
		OR (i.ZWM_VolumetricWeight IS NULL AND @CtrlVolWeight = 1)
		OR (i.lot_attr_group)IS NOT NULL)
	END
	------------------------------------------------------------------------------------------------- /GRN
	
	------------------------------------------------------------------------------------------------- ITEM

	IF @ItemStart is not null OR @ItemEnd is not null
	BEGIN
   
		SET @ItemStart = ISNULL(dbo.ExpandKyByType('ItemType', @ItemStart), dbo.LowString('ItemType'))   
		SET @ItemEnd = ISNULL(dbo.ExpandKyByType('ItemType', @ItemEnd), dbo.LowString('ItemType'))  

		INSERT INTO #tempTable 
		(Articulo,UMStock1,AnchoStk1,AltoStk1,ProfStk1,UMStock2,AnchoStk2,AltoStk2,ProfStk2,Peso,CodBar,PesoAfor,Ranking,AtributLote)
		SELECT distinct(i.item),i.ZWM_UMStock1,i.ZWM_Stk1Width,i.ZWM_Stk1Height,i.ZWM_Stk1Depth,i.ZWM_UMStock2,i.ZWM_Stk2Width,i.ZWM_Stk2Height,i.ZWM_Stk2Depth,i.unit_weight,i.ZWM_BarCode,i.ZWM_VolumetricWeight,
		iw.ranking,i.lot_attr_group
		FROM item i
		INNER JOIN zwm_itm_whse iw
		ON i.item = iw.item
		INNER JOIN poitem poi
		ON i.item = poi.item
		WHERE poi.po_num BETWEEN @ItemStart AND @ItemEnd
		AND(
		(i.ZWM_UMStock1 IS NULL AND @CtrlUMStock1 = 1)
		OR (i.ZWM_Stk1Width IS NULL OR i.ZWM_Stk1Height IS NULL OR i.ZWM_Stk1Depth IS NULL AND @CtrlDimStock1 = 1)
		OR (i.ZWM_UMStock2 IS NULL AND @CtrlUMStock2 = 1)
		OR (i.ZWM_Stk2Width IS NULL OR i.ZWM_Stk2Height IS NULL OR i.ZWM_Stk2Depth IS NULL AND @CtrlDimStock2 = 1)
		OR (i.unit_weight IS NULL OR i.unit_weight=0 AND @CtrlWeight = 1)
		OR (i.ZWM_BarCode IS NULL AND @CtrlBarCode = 1)
		OR (iw.ranking IS NULL AND @CtrlSeqStor = 1)
		OR (i.ZWM_VolumetricWeight IS NULL AND @CtrlVolWeight = 1)
		OR (i.lot_attr_group)IS NOT NULL)
	END
   ------------------------------------------------------------------------------------------------- /ITEM
		
   select * from #tempTable
   

GO


