/****** Object:  StoredProcedure [dbo].[ZWM_Rpt_ItemStorageReportSp]    Script Date: 01/09/2015 14:57:38 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ZWM_Rpt_ItemStorageReportSp]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[ZWM_Rpt_ItemStorageReportSp]
GO

/****** Object:  StoredProcedure [dbo].[ZWM_Rpt_ItemStorageReportSp]    Script Date: 01/09/2015 14:57:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[ZWM_Rpt_ItemStorageReportSp]( 
	@POStart			PoNumType = NULL
	,@POEnd				PoNumType = NULL
	,@GRNStart			GrnNumType = NULL
	,@GRNEnd			GrnNumType = NULL
	,@ItemStart			ItemType = NULL
	,@ItemEnd			ItemType = NULL
	,@CtrlUMStock1		FlagNyType = 0
	,@CtrlDimStock1		FlagNyType = 0
	,@CtrlUMStock2		FlagNyType = 0
	,@CtrlDimStock2		FlagNyType = 0
	,@CtrlWeight		FlagNyType = 0
	,@CtrlBarCode		FlagNyType = 0
	,@CtrlSeqStor		FlagNyType = 0
	,@CtrlVolWeight		FlagNyType = 0
	,@CtrlVolVol		FlagNyType = 0
	,@CtrlFamCode		FlagNyType = 0
	,@Whse				WhseType = NULL
	,@Exceptions		FlagNyType = 0
	,@ZwmFrom			char(1) = NULL
	,@pSite				SiteType
)
AS

-- Check for existence of Generic External Touch Point routine (this section was generated by SpETPCodeSp and inserted by CallETPs.exe):
   IF OBJECT_ID(N'dbo.EXTGEN_ZWM_Rpt_ItemStorageReportSp') IS NOT NULL
   BEGIN
      DECLARE @EXTGEN_SpName sysname
      SET @EXTGEN_SpName = N'dbo.EXTGEN_ZWM_Rpt_ItemStorageReportSp'
      -- Invoke the ETP routine, passing in (and out) this routine's parameters:
      DECLARE @EXTGEN_Severity int
      EXEC @EXTGEN_Severity = @EXTGEN_SpName
		@POStart
		,@POEnd	
		,@GRNStart
		,@GRNEnd
		,@ItemStart
		,@ItemEnd
		,@CtrlUMStock1
		,@CtrlDimStock1
		,@CtrlUMStock2
		,@CtrlDimStock2
		,@CtrlWeight
		,@CtrlBarCode
		,@CtrlSeqStor
		,@CtrlVolWeight
		,@CtrlVolVol
		,@CtrlFamCode
		,@Whse
		,@Exceptions
		,@ZwmFrom
		,@pSite
		--,@Infobar
		
       -- ETP routine can RETURN 1 to signal that the remainder of this standard routine should now proceed:
      IF @EXTGEN_Severity <> 1
         RETURN @EXTGEN_Severity
   END
   -- End of Generic External Touch Point code.


-- A session context is created so session variables can be used.
DECLARE
     @RptSessionID RowPointerType

EXEC dbo.InitSessionContextSp
     @ContextName = 'ZWM'
   , @SessionID   = @RptSessionID    OUTPUT
   , @Site        = @pSite

Declare @infobar InfobarType
Declare @Severity int
Set @Severity = 0

SET @POStart = ISNULL(dbo.ExpandKyByType('PoNumType', @POStart), dbo.LowString('PoNumType'))
SET @POEnd = ISNULL(dbo.ExpandKyByType('PoNumType', @POEnd), dbo.HighString('PoNumType'))  
SET @GRNStart = ISNULL(@GRNStart, dbo.LowString('GrnNumType'))   
SET @GRNEnd = ISNULL(@GRNEnd, dbo.HighString('GrnNumType')) 
SET @ItemStart = ISNULL(@ItemStart, dbo.LowString('ItemType'))
SET @ItemEnd = ISNULL(@ItemEnd, dbo.HighString('ItemType'))

   CREATE TABLE #tempTable
   (Articulo nvarchar(30)
   , Descripcion nvarchar(40)

   , UMStock1 nvarchar(30)
   , AnchoStk1 nvarchar(30), AltoStk1 nvarchar(30), ProfStk1 nvarchar(30)
   , UMStock2 nvarchar(30)
   , AnchoStk2 nvarchar(30), AltoStk2 nvarchar(30), ProfStk2 nvarchar(30)
   , CodBar nvarchar(40)
   , PesoUnit nvarchar(30)
   , VolUnit nvarchar(30)
   , PesoAfor nvarchar(30)
   , FamilyCode nvarchar(30)
   
   , Ranking nvarchar(30)
   , Whse nvarchar(30)
   , Zona nvarchar(30))
   
   
   ------------------------------------------------------------------------------------------------- PURCHASE ORDER
   
   IF @ZwmFrom = 'P'
   BEGIN
		INSERT INTO #tempTable 
		(Articulo
		,Descripcion
		,UMStock1
		,AnchoStk1,AltoStk1,ProfStk1
		,UMStock2
		,AnchoStk2,AltoStk2,ProfStk2
		,CodBar
		,PesoUnit
		,VolUnit
		,PesoAfor
		,FamilyCode
		,Ranking
		,Whse
		,Zona)
		SELECT distinct i.item, i.description
		,isnull(cast(i.ZWM_UMStock1 as nvarchar(30)),'No Definido')
		,isnull(cast(i.ZWM_Stk1Width as nvarchar)+' '+zp.um_dimension_stock1,'No Definido'),isnull(cast(i.ZWM_Stk1Height as nvarchar)+' '+zp.um_dimension_stock1,'No Definido'),isnull(cast(i.ZWM_Stk1Depth as nvarchar)+' '+zp.um_dimension_stock1,'No Definido')
		,isnull(cast(i.ZWM_UMStock2 as nvarchar(30)),'No Definido')
		,isnull(cast(i.ZWM_Stk2Width as nvarchar)+' '+zp.um_dimension_stock1,'No Definido'),isnull(cast(i.ZWM_Stk2Height as nvarchar)+' '+zp.um_dimension_stock1,'No Definido'),isnull(cast(i.ZWM_Stk2Depth as nvarchar)+' '+zp.um_dimension_stock1,'No Definido')
		,isnull(i.ZWM_BarCode, 'No Definido')
		,isnull(cast(i.unit_weight as nvarchar)+' '+weight_units, 'No Definido') 
		,isnull(cast(i.ZWM_VolVol as nvarchar)+' '+zp.um_vol, 'No Definido')
		,isnull(cast(dbo.ZWM_VolumetricWeight(i.item) as nvarchar)+' '+zp.um_weight,'No Definido')
		,isnull(cast(i.family_code as nvarchar(30)),'No Definido')
		,Ranking =
		case when isnull(iwi.ranking,iwf.ranking) is null then 'No Definido'
			 else cast(isnull(iwi.ranking,iwf.ranking) as nvarchar)
			 end
		,isnull(iwi.whse,iwf.whse)
		,isnull(isnull(isnull(iwi.zone,iwi.location),iwf.zone),iwf.location)
		FROM item i
		CROSS JOIN zwm_parms zp
		LEFT JOIN zwm_itm_whse iwi on iwi.item = i.item and iwi.whse = @Whse
		LEFT JOIN zwm_itm_whse iwf on iwf.family_code = i.family_code and iwf.whse = @Whse
		INNER JOIN poitem poi
		ON i.item = poi.item
		WHERE poi.po_num BETWEEN @POStart AND @POEnd
		AND
		(
		(@Exceptions = 0)
		OR
		(
		(i.ZWM_UMStock1 IS NULL AND @CtrlUMStock1 = 1)
		OR ((i.ZWM_Stk1Width IS NULL OR i.ZWM_Stk1Height IS NULL OR i.ZWM_Stk1Depth IS NULL OR i.ZWM_Stk1Width = 0 OR i.ZWM_Stk1Height = 0 OR i.ZWM_Stk1Depth = 0) AND @CtrlDimStock1 = 1)
		OR (i.ZWM_UMStock2 IS NULL AND @CtrlUMStock2 = 1)
		OR ((i.ZWM_Stk2Width IS NULL OR i.ZWM_Stk2Height IS NULL OR i.ZWM_Stk2Depth IS NULL OR i.ZWM_Stk2Width = 0 OR i.ZWM_Stk2Height = 0 OR i.ZWM_Stk2Depth = 0) AND @CtrlDimStock2 = 1)
		OR (i.ZWM_BarCode IS NULL AND @CtrlBarCode = 1)
		OR ((i.unit_weight IS NULL OR i.unit_weight=0) AND @CtrlWeight = 1)
		OR ((dbo.ZWM_VolumetricWeight(i.item) IS NULL OR dbo.ZWM_VolumetricWeight(i.item) = 0) AND @CtrlVolWeight = 1)
		OR (i.family_code IS NULL AND @CtrlFamCode = 1)
		OR (isnull(iwi.ranking,iwf.ranking) = null AND @CtrlSeqStor = 1)
		))
		ORDER BY i.item
   END
   ------------------------------------------------------------------------------------------------- /PURCHASE ORDER
   
   ------------------------------------------------------------------------------------------------- GRN
   IF @ZwmFrom = 'G'
   BEGIN
		
		INSERT INTO #tempTable 
		(Articulo
		,Descripcion
		,UMStock1
		,AnchoStk1,AltoStk1,ProfStk1
		,UMStock2
		,AnchoStk2,AltoStk2,ProfStk2
		,CodBar
		,PesoUnit
		,VolUnit
		,PesoAfor
		,FamilyCode
		,Ranking
		,Whse
		,Zona)
		SELECT distinct i.item, i.description
		,isnull(cast(i.ZWM_UMStock1 as nvarchar(30)),'No Definido')
		,isnull(cast(i.ZWM_Stk1Width as nvarchar)+' '+zp.um_dimension_stock1,'No Definido'),isnull(cast(i.ZWM_Stk1Height as nvarchar)+' '+zp.um_dimension_stock1,'No Definido'),isnull(cast(i.ZWM_Stk1Depth as nvarchar)+' '+zp.um_dimension_stock1,'No Definido')
		,isnull(cast(i.ZWM_UMStock2 as nvarchar(30)),'No Definido')
		,isnull(cast(i.ZWM_Stk2Width as nvarchar)+' '+zp.um_dimension_stock1,'No Definido'),isnull(cast(i.ZWM_Stk2Height as nvarchar)+' '+zp.um_dimension_stock1,'No Definido'),isnull(cast(i.ZWM_Stk2Depth as nvarchar)+' '+zp.um_dimension_stock1,'No Definido')
		,isnull(i.ZWM_BarCode, 'No Definido')
		,isnull(cast(i.unit_weight as nvarchar)+' '+weight_units, 'No Definido') 
		,isnull(cast(i.ZWM_VolVol as nvarchar)+' '+zp.um_vol, 'No Definido')
		,isnull(cast(dbo.ZWM_VolumetricWeight(i.item) as nvarchar)+' '+zp.um_weight,'No Definido')
		,isnull(cast(i.family_code as nvarchar(30)),'No Definido')
		,Ranking =
		case when isnull(iwi.ranking,iwf.ranking) is null then 'No Definido'
			 else cast(isnull(iwi.ranking,iwf.ranking) as nvarchar)
			 end
		,isnull(iwi.whse,iwf.whse)
		,isnull(isnull(isnull(iwi.zone,iwi.location),iwf.zone),iwf.location)
		FROM item i
		CROSS JOIN zwm_parms zp
		LEFT JOIN zwm_itm_whse iwi on iwi.item = i.item and iwi.whse = @Whse
		LEFT JOIN zwm_itm_whse iwf on iwf.family_code = i.family_code and iwf.whse = @Whse
		INNER JOIN poitem poi
		ON i.item = poi.item
		INNER JOIN grn_line grn
		ON grn.po_num = poi.po_num
		WHERE grn.grn_num BETWEEN @GRNStart AND @GRNEnd
		AND
		(
		(@Exceptions = 0)
		OR
		(
		(i.ZWM_UMStock1 IS NULL AND @CtrlUMStock1 = 1)
		OR ((i.ZWM_Stk1Width IS NULL OR i.ZWM_Stk1Height IS NULL OR i.ZWM_Stk1Depth IS NULL OR i.ZWM_Stk1Width = 0 OR i.ZWM_Stk1Height = 0 OR i.ZWM_Stk1Depth = 0) AND @CtrlDimStock1 = 1)
		OR (i.ZWM_UMStock2 IS NULL AND @CtrlUMStock2 = 1)
		OR ((i.ZWM_Stk2Width IS NULL OR i.ZWM_Stk2Height IS NULL OR i.ZWM_Stk2Depth IS NULL OR i.ZWM_Stk2Width = 0 OR i.ZWM_Stk2Height = 0 OR i.ZWM_Stk2Depth = 0) AND @CtrlDimStock2 = 1)
		OR (i.ZWM_BarCode IS NULL AND @CtrlBarCode = 1)
		OR ((i.unit_weight IS NULL OR i.unit_weight=0) AND @CtrlWeight = 1)
		OR ((dbo.ZWM_VolumetricWeight(i.item) IS NULL OR dbo.ZWM_VolumetricWeight(i.item) = 0) AND @CtrlVolWeight = 1)
		OR (i.family_code IS NULL AND @CtrlFamCode = 1)
		OR (isnull(iwi.ranking,iwf.ranking) = null AND @CtrlSeqStor = 1)
		))
		ORDER BY i.item
	END
	------------------------------------------------------------------------------------------------- /GRN
	
	------------------------------------------------------------------------------------------------- ITEM

   IF @ZwmFrom = 'I'
	BEGIN		
		SET @ItemStart = ISNULL(@ItemStart, dbo.LowString('ItemType'))
		SET @ItemEnd = ISNULL(@ItemEnd, dbo.HighString('ItemType'))

		INSERT INTO #tempTable 
		(Articulo
		,Descripcion
		,UMStock1
		,AnchoStk1,AltoStk1,ProfStk1
		,UMStock2
		,AnchoStk2,AltoStk2,ProfStk2
		,CodBar
		,PesoUnit
		,VolUnit
		,PesoAfor
		,FamilyCode
		,Ranking
		,Whse
		,Zona)
		SELECT distinct i.item, i.description
		,isnull(cast(i.ZWM_UMStock1 as nvarchar(30)),'No Definido')
		,isnull(cast(i.ZWM_Stk1Width as nvarchar)+' '+zp.um_dimension_stock1,'No Definido'),isnull(cast(i.ZWM_Stk1Height as nvarchar)+' '+zp.um_dimension_stock1,'No Definido'),isnull(cast(i.ZWM_Stk1Depth as nvarchar)+' '+zp.um_dimension_stock1,'No Definido')
		,isnull(cast(i.ZWM_UMStock2 as nvarchar(30)),'No Definido')
		,isnull(cast(i.ZWM_Stk2Width as nvarchar)+' '+zp.um_dimension_stock1,'No Definido'),isnull(cast(i.ZWM_Stk2Height as nvarchar)+' '+zp.um_dimension_stock1,'No Definido'),isnull(cast(i.ZWM_Stk2Depth as nvarchar)+' '+zp.um_dimension_stock1,'No Definido')
		,isnull(i.ZWM_BarCode, 'No Definido')
		,isnull(cast(i.unit_weight as nvarchar)+' '+weight_units, 'No Definido') 
		,isnull(cast(i.ZWM_VolVol as nvarchar)+' '+zp.um_vol, 'No Definido')
		,isnull(cast(dbo.ZWM_VolumetricWeight(i.item) as nvarchar)+' '+zp.um_weight,'No Definido')
		,isnull(cast(i.family_code as nvarchar(30)),'No Definido')
		,Ranking =
		case when isnull(iwi.ranking,iwf.ranking) is null then 'No Definido'
			 else cast(isnull(iwi.ranking,iwf.ranking) as nvarchar)
			 end
		,isnull(iwi.whse,iwf.whse)
		,isnull(isnull(isnull(iwi.zone,iwi.location),iwf.zone),iwf.location)
		FROM item i
		CROSS JOIN zwm_parms zp
		LEFT JOIN zwm_itm_whse iwi on iwi.item = i.item and iwi.whse = @Whse
		LEFT JOIN zwm_itm_whse iwf on iwf.family_code = i.family_code and iwf.whse = @Whse
		WHERE i.item BETWEEN @ItemStart AND @ItemEnd
		AND
		(
		(@Exceptions = 0)
		OR
		(
		(i.ZWM_UMStock1 IS NULL AND @CtrlUMStock1 = 1)
		OR ((i.ZWM_Stk1Width IS NULL OR i.ZWM_Stk1Height IS NULL OR i.ZWM_Stk1Depth IS NULL OR i.ZWM_Stk1Width = 0 OR i.ZWM_Stk1Height = 0 OR i.ZWM_Stk1Depth = 0) AND @CtrlDimStock1 = 1)
		OR (i.ZWM_UMStock2 IS NULL AND @CtrlUMStock2 = 1)
		OR ((i.ZWM_Stk2Width IS NULL OR i.ZWM_Stk2Height IS NULL OR i.ZWM_Stk2Depth IS NULL OR i.ZWM_Stk2Width = 0 OR i.ZWM_Stk2Height = 0 OR i.ZWM_Stk2Depth = 0) AND @CtrlDimStock2 = 1)
		OR (i.ZWM_BarCode IS NULL AND @CtrlBarCode = 1)
		OR ((i.unit_weight IS NULL OR i.unit_weight=0) AND @CtrlWeight = 1)
		OR ((dbo.ZWM_VolumetricWeight(i.item) IS NULL OR dbo.ZWM_VolumetricWeight(i.item) = 0) AND @CtrlVolWeight = 1)
		OR (i.family_code IS NULL AND @CtrlFamCode = 1)
		OR (isnull(iwi.ranking,iwf.ranking) = null AND @CtrlSeqStor = 1)
		))
		ORDER BY i.item
	END
	
   ------------------------------------------------------------------------------------------------- /ITEM
		
   select * from #tempTable
   DROP TABLE #tempTable   

   EXEC dbo.CloseSessionContextSp @SessionID = @RptSessionID

GO


