/****** Object:  StoredProcedure [dbo].[ZWM_RFRecConsReport2Sp]    Script Date: 01/20/2015 15:15:46 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ZWM_RFRecConsReport2Sp]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[ZWM_RFRecConsReport2Sp]
GO

/****** Object:  StoredProcedure [dbo].[ZWM_RFRecConsReport2Sp]    Script Date: 01/20/2015 15:15:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[ZWM_RFRecConsReport2Sp] (
	@Site         SiteType
	,@IdRecCons	  ZwmIdRFConsType   = NULL
	,@Infobar     InfobarType       = NULL OUTPUT	
)
AS

DECLARE @BinVar varbinary(128)
SET @BinVar = CAST(@Site AS varbinary(128))
SET CONTEXT_INFO @BinVar

DECLARE @Severity int
SET @Severity = 0

 -- Check for existence of Generic External Touch Point routine (this section was generated by SpETPCodeSp and inserted by CallETPs.exe):
   IF OBJECT_ID(N'dbo.EXTGEN_ZWM_RFRecConsReport2Sp') IS NOT NULL
   BEGIN
      DECLARE @EXTGEN_SpName sysname
      SET @EXTGEN_SpName = N'dbo.EXTGEN_ZWM_RFRecConsReport2Sp'
      -- Invoke the ETP routine, passing in (and out) this routine's parameters:
      DECLARE @EXTGEN_Severity int
      EXEC @EXTGEN_Severity = @EXTGEN_SpName
		@Site
		,@IdRecCons
		,@Infobar	OUTPUT
 
      -- ETP routine can RETURN 1 to signal that the remainder of this standard routine should now proceed:
      IF @EXTGEN_Severity <> 1
         RETURN @EXTGEN_Severity
   END
   -- End of Generic External Touch Point code.
   
------------------------------ SET NULLs
IF LEN(LTRIM(@IdRecCons	)) = 0 SET @IdRecCons = NULL
------------------------------ SET NULLs
   
 SELECT 
 rf.id_rec_cons AS id
 , rf.grn_num AS GRN
 , grn.vend_num AS Proveedor
 , grn.ZWM_packNumber AS Remito
 , vendaddr.name AS Nombre
 FROM  
 zwm_tmp_rf_cons1_mst rf
 INNER JOIN  grn_hdr grn ON grn.grn_num = rf.grn_num
 LEFT JOIN vendaddr
 ON vendaddr.vend_num = grn.vend_num
 WHERE rf.id_rec_cons = @IdRecCons
GO


