/****** Object:  StoredProcedure [dbo].[ZWM_RF_Picking1Sp]    Script Date: 01/30/2015 10:50:35 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ZWM_RF_Picking1Sp]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[ZWM_RF_Picking1Sp]
GO

/****** Object:  StoredProcedure [dbo].[ZWM_RF_Picking1Sp]    Script Date: 01/30/2015 10:50:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[ZWM_RF_Picking1Sp] (
     @Site				SiteType
	,@UserName			UserNameType			= NULL
	,@PickListID		PickListIDType			= NULL
	,@Seq				PickListSequenceType	= NULL
	,@RefType			RefType					= NULL-- 'T' = Transferencia, 'O' = Orden de venta
	,@RefNum			CoNumType				= NULL
	,@RefLine			CoLineType				= NULL
	,@RefRelease		CoReleaseType			= NULL
	,@Zone				DescriptionType			= NULL
	,@whse				WhseType				= NULL OUTPUT
    ,@Loc				LocType					= NULL OUTPUT
    ,@Item				ItemType				= NULL OUTPUT
    ,@Lot				LotType					= NULL OUTPUT
    ,@Qty				QtyUnitType				= NULL OUTPUT
    ,@um				UMType					= NULL OUTPUT
	,@From				char(1)					= NULL --indica si se debe tomar el dato de las reservas o de la tabla de picklist
    ,@Infobar			InfobarType				= NULL OUTPUT
)
AS

 -- Check for existence of Generic External Touch Point routine (this section was generated by SpETPCodeSp and inserted by CallETPs.exe):
   IF OBJECT_ID(N'dbo.EXTGEN_ZWM_RF_Picking1Sp') IS NOT NULL
   BEGIN
      DECLARE @EXTGEN_SpName sysname
      SET @EXTGEN_SpName = N'dbo.EXTGEN_ZWM_RF_Picking1Sp'
      -- Invoke the ETP routine, passing in (and out) this routine's parameters:
      DECLARE @EXTGEN_Severity int
      EXEC @EXTGEN_Severity = @EXTGEN_SpName
		 @Site				
		,@UserName			
		,@PickListID		
		,@Seq				
		,@RefType
		,@RefNum				
		,@RefLine			
		,@RefRelease			
		,@Zone
		,@whse				OUTPUT
		,@Loc				OUTPUT
		,@Item				OUTPUT
		,@Lot				OUTPUT
		,@Qty				OUTPUT
		,@um				OUTPUT
		,@From
		,@Infobar			OUTPUT	
 
      -- ETP routine can RETURN 1 to signal that the remainder of this standard routine should now proceed:
      IF @EXTGEN_Severity <> 1
         RETURN @EXTGEN_Severity
   END
   -- End of Generic External Touch Point code.

--Setea Null en parámetros de Entrada
IF LEN(LTRIM(RTRIM(@UserName))) = 0
	SET @UserName = NULL
IF LEN(LTRIM(RTRIM(@PickListID))) = 0
	SET @PickListID = NULL
IF LEN(LTRIM(RTRIM(@Seq))) = 0
	SET @Seq = NULL
IF LEN(LTRIM(RTRIM(@RefNum))) = 0
	SET @RefNum = NULL
IF LEN(LTRIM(RTRIM(@RefLine))) = 0
	SET @RefLine = NULL
IF LEN(LTRIM(RTRIM(@RefRelease))) = 0
	SET @RefRelease = NULL
IF LEN(LTRIM(RTRIM(@Zone))) = 0
	SET @Zone = NULL
IF LEN(LTRIM(RTRIM(@From))) = 0
	SET @From = NULL

--Inicio de Sesion
DECLARE	@return_value int,
		@sessionId            RowPointerType

SET @UserName = isnull(@UserName,'sa')

EXEC	@return_value = [dbo].[InitSessionContextWithUserSp]
		@ContextName = 'ZWM',
		@UserName = @UserName,
		@SessionID = @SessionID OUTPUT,
		@Site = @Site

--Solo para implementacion Barugel Azulay
DECLARE @BAR FlagNyTYpe
IF (Select count(*) from zwm_parms where customer = 'BAR') > 0
	Set @BAR = 1 

DECLARE @Severity int
SET @Severity = 0

SET @Lot = dbo.ExpandKyByType('LotType',@Lot)
IF @RefType = 'O'
	SET @RefNum = dbo.ExpandKyByType('CoNumType',@RefNum)	
IF @RefType = 'T'
	SET @RefNum = dbo.ExpandKyByType('TrnNumType',@RefNum)	

IF	(@PickListID IS NULL OR @Seq IS NULL) AND (@RefType = 'O' AND (@RefNum IS NULL OR @RefLine IS NULL OR @RefRelease IS NULL)) AND (@RefType = 'T' AND (@RefNum IS NULL OR @RefLine IS NULL))
BEGIN
	SET @Infobar = 'Debe ingresar datos de referencia'
	SET @Severity = 16
	RETURN @Severity
END

IF (@PickListID IS NULL OR @Seq IS NULL)
BEGIN
	SELECT @PickListID = plr.pick_list_id, @Seq = plr.sequence
	FROM pick_list_ref plr JOIN pick_list pl on plr.pick_list_id = pl.pick_list_id
	WHERE 
	(@RefType = 'O' and plr.ref_num = @RefNum AND plr.ref_line_suf = @RefLine AND plr.ref_release = @RefRelease AND pl.status = 'O')
	OR
	(@RefType = 'T' and plr.ref_num = @RefNum AND plr.ref_line_suf = @RefLine and pl.status = 'O')
END

IF (select count(pick_list_id)FROM pick_list_ref where pick_list_id = @PickListID and sequence = @Seq) = 0
BEGIN
	SET @Infobar = 'No Existen los datos de referencia'
	SET @Severity = 16
	RETURN @Severity
END

IF (select status FROM pick_list_ref plr join pick_list pl on pl.pick_list_id = plr.pick_list_id 
where plr.pick_list_id = @PickListID and plr.sequence = @Seq) != 'O'
BEGIN
	SET @Infobar = 'El Pickeo esta cerrado'
	SET @Severity = 16
	RETURN @Severity
END

BEGIN

	SELECT TOP 1
	@item = i.item
	,@whse = pl.whse
	,@loc = pll.loc
	,@lot = pll.lot
	,@qty = (pll.qty_to_pick - pll.qty_picked)
	,@um = i.u_m
	FROM 
	pick_list pl
	JOIN pick_list_ref plr
	ON pl.pick_list_id = plr.pick_list_id
	JOIN pick_list_loc pll
	ON pl.pick_list_id = pll.pick_list_id
	LEFT JOIN coitem coi
	ON plr.ref_num = coi.co_num and plr.ref_line_suf = coi.co_line and plr.ref_release = coi.co_release
	LEFT JOIN trnitem trni
	ON plr.ref_num = trni.trn_num and plr.ref_line_suf = trni.trn_line
	JOIN item i
	ON coi.item = i.item
	WHERE pll.pick_list_id = @PickListID and pll.sequence = @Seq
	AND pll.qty_to_pick > pll.qty_picked

END

EXEC dbo.CloseSessionContextSp @SessionID = @SessionID
GO


