/****** Object:  StoredProcedure [dbo].[ZWM_RFItemBarCode2Sp]    Script Date: 01/20/2015 15:13:09 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ZWM_RFItemBarCode2Sp]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[ZWM_RFItemBarCode2Sp]
GO

/****** Object:  StoredProcedure [dbo].[ZWM_RFItemBarCode2Sp]    Script Date: 01/20/2015 15:13:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[ZWM_RFItemBarCode2Sp] (
	  @Site		         SiteType	
	, @UserName			 UserNameType	= NULL
    , @ItemBarCode	     ZwmBarCodeType 
	, @ItemItem		     ItemType
	, @Post				 FlagNyType		= 0
	, @Infobar           InfobarType	= NULL OUTPUT
)
AS

   -- Check for existence of Generic External Touch Point routine (this section was generated by SpETPCodeSp and inserted by CallETPs.exe):
   IF OBJECT_ID(N'dbo.EXTGEN_ZWM_RFItemBarCode2Sp') IS NOT NULL
   BEGIN
      DECLARE @EXTGEN_SpName sysname
      SET @EXTGEN_SpName = N'dbo.EXTGEN_ZWM_RFItemBarCode2Sp'
      -- Invoke the ETP routine, passing in (and out) this routine's parameters:
      DECLARE @EXTGEN_Severity int
      EXEC @EXTGEN_Severity = @EXTGEN_SpName
			  @Site
			, @UserName
			, @ItemBarCode	     
			, @ItemItem
			, @Post			 
			, @Infobar			 OUTPUT
	      
      -- ETP routine can RETURN 1 to signal that the remainder of this standard routine should now proceed:
      IF @EXTGEN_Severity <> 1
         RETURN @EXTGEN_Severity
   END
   -- End of Generic External Touch Point code.


--Inicio de Sesion
DECLARE	@return_value int,
		@sessionId            RowPointerType

SET @UserName = isnull(@UserName,'sa')

EXEC	@return_value = [dbo].[InitSessionContextWithUserSp]
		@ContextName = 'ZWM',
		@UserName = @UserName,
		@SessionID = @SessionID OUTPUT,
		@Site = @Site

--Solo para implementacion Barugel Azulay
DECLARE @BAR FlagNyTYpe
IF (Select count(*) from zwm_parms where customer = 'BAR') > 0
	Set @BAR = 1 


DECLARE
 @Severity          int
,@ItemRowPointer	RowPointerType
,@BarCode			ZwmBarCodeType
,@OtherItem			ItemType
	
SET @Severity = 0

	SELECT @ItemRowPointer = RowPointer, @BarCode = ZWM_BarCode
	FROM item
	WHERE item = @ItemItem
	
	SELECT @OtherItem = item
	FROM item
	WHERE ZWM_BarCode = @ItemBarCode
	
		
	IF @ItemRowPointer IS NULL
		BEGIN
			SET @Severity = 16
			SET @Infobar = 'El artículo ' + @ItemItem + ' no existe'
		END
	ELSE IF @OtherItem <> @ItemItem
		BEGIN
			SET @Severity = 16
			
			IF @BAR = 1
				SET @Infobar = 'CodBar utilizado ' + @OtherItem
			ELSE
				SET @Infobar = 'El código de barras ' + @ItemBarCode + ' está asignado al artículo ' + @OtherItem
			
		END
	ELSE IF @BarCode <> @ItemBarCode
		BEGIN
			SET @Severity = 1
			
			IF @BAR = 1
				set @Infobar = 'Articulo ya asociado F5 Acepta'
			Else
				set @Infobar = 'El artículo "' + @ItemItem + '" tiene asignado el código de barras "' + @BarCode + '"'
		END

	IF @Post = 1
		BEGIN
			UPDATE item SET ZWM_BarCode = @ItemBarCode
			WHERE item = @ItemItem
						
			SET @Infobar = 'El código de barras '+ @ItemBarCode + ' se asignó correctamente al artículo '+ @ItemItem
		END

EXEC dbo.CloseSessionContextSp @SessionID = @SessionID

RETURN @Severity
GO


