/****** Object:  StoredProcedure [dbo].[ZWM_RFUserWhseSp]    Script Date: 01/20/2015 15:17:04 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ZWM_RFUserWhseSp]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[ZWM_RFUserWhseSp]
GO

/****** Object:  StoredProcedure [dbo].[ZWM_RFUserWhseSp]    Script Date: 01/20/2015 15:17:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[ZWM_RFUserWhseSp] (
  @Site		         SiteType	
, @UserName			 UserNameType	= NULL
, @Whse				 WhseType		= NULL OUTPUT	
, @Infobar           InfobarType	= NULL OUTPUT
)
AS

   -- Check for existence of Generic External Touch Point routine (this section was generated by SpETPCodeSp and inserted by CallETPs.exe):
   IF OBJECT_ID(N'dbo.EXTGEN_ZWM_RFUserWhseSp') IS NOT NULL
   BEGIN
      DECLARE @EXTGEN_SpName sysname
      SET @EXTGEN_SpName = N'dbo.EXTGEN_ZWM_RFUserWhseSp'
      -- Invoke the ETP routine, passing in (and out) this routine's parameters:
      DECLARE @EXTGEN_Severity int
      EXEC @EXTGEN_Severity = @EXTGEN_SpName
			  @Site
			, @UserName
			, @Whse				 OUTPUT
			, @Infobar           OUTPUT
 
      -- ETP routine can RETURN 1 to signal that the remainder of this standard routine should now proceed:
      IF @EXTGEN_Severity <> 1
         RETURN @EXTGEN_Severity
   END
   -- End of Generic External Touch Point code.

--Inicio de Sesion
DECLARE	@return_value int,
		@sessionId            RowPointerType

EXEC	@return_value = [dbo].[InitSessionContextWithUserSp]
		@ContextName = 'ZWM',
		@UserName = @UserName,
		@SessionID = @SessionID OUTPUT,
		@Site = @Site

--Solo para implementacion Barugel Azulay
DECLARE @BAR FlagNyTYpe
IF (SELECT count(*) FROM zwm_parms WHERE customer = 'BAR') > 0
	Set @BAR = 1 

DECLARE
 @Severity int	
SET @Severity = 0

------------------------------ SET NULLs
IF LEN(LTRIM(@UserName)) = 0 SET @UserName = NULL
------------------------------ SET NULLs

IF (SELECT count(*) FROM usernames WHERE Username = @UserName) = 0
BEGIN
	SET @Infobar = 'El usuario no existe en SyteLine'
	SET @Severity = 16
END
ELSE IF (SELECT whse FROM user_local ul JOIN usernames un on un.userid = ul.userid WHERE un.Username = @UserName) IS NULL
BEGIN 
	SET @Infobar = 'El usuario no tiene seteado depósito default'
	SET @Severity = 16
END
ELSE 
BEGIN 
	SELECT @Whse = whse FROM user_local ul JOIN usernames un on un.userid = ul.userid WHERE un.Username = @UserName
	SET @Severity = 0
END

EXEC dbo.CloseSessionContextSp @SessionID = @SessionID
	
RETURN @Severity
GO


