/****** Object:  StoredProcedure [dbo].[ZWM_RFCyCleWhseSp]    Script Date: 01/20/2015 15:12:32 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ZWM_RFCyCleWhseSp]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[ZWM_RFCyCleWhseSp]
GO

/****** Object:  StoredProcedure [dbo].[ZWM_RFCyCleWhseSp]    Script Date: 01/20/2015 15:12:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[ZWM_RFCyCleWhseSp](
     @Site			 SiteType
	,@UserName		 UserNameType = NULL
	,@Whse			 WhseType = NULL
	,@Infobar		 InfobarType = NULL OUTPUT
)
AS

   -- Check for existence of Generic External Touch Point routine (this section was generated by SpETPCodeSp and inserted by CallETPs.exe):
   IF OBJECT_ID(N'dbo.EXTGEN_ZWM_RFCyCleWhseSp') IS NOT NULL
   BEGIN
      DECLARE @EXTGEN_SpName sysname
      SET @EXTGEN_SpName = N'dbo.EXTGEN_ZWM_RFCyCleWhseSp'
      -- Invoke the ETP routine, passing in (and out) this routine's parameters:
      DECLARE @EXTGEN_Severity int
      EXEC @EXTGEN_Severity = @EXTGEN_SpName
	     @Site
		,@UserName
		,@Whse
		,@Infobar
 
      -- ETP routine can RETURN 1 to signal that the remainder of this standard routine should now proceed:
      IF @EXTGEN_Severity <> 1
         RETURN @EXTGEN_Severity
   END
   -- End of Generic External Touch Point code.

--Inicio de Sesion
DECLARE	@return_value int,
		@sessionId            RowPointerType

SET @UserName = isnull(@UserName,'sa')

EXEC	@return_value = [dbo].[InitSessionContextWithUserSp]
		@ContextName = 'ZWM',
		@UserName = @UserName,
		@SessionID = @SessionID OUTPUT,
		@Site = @Site

--Solo para implementacion Barugel Azulay
DECLARE @BAR FlagNyTYpe
IF (Select count(*) from zwm_parms where customer = 'BAR') > 0
	Set @BAR = 1 


----------------------------------------------------------------------- VARIABLES
DECLARE @Severity int
SET @Severity = 0

IF(SELECT Count(*) FROM Cycle WHERE whse = @Whse) = 0
BEGIN
	SET @Infobar = 'Conteo no habilitado para este almacén'
	SET @Severity = 16
	RETURN @severity
END

EXEC dbo.CloseSessionContextSp @SessionID = @SessionID

RETURN @Severity
GO


