/****** Object:  StoredProcedure [dbo].[ZWM_GenerateTransferOrder]    Script Date: 01/09/2015 14:42:18 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ZWM_GenerateTransferOrder]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[ZWM_GenerateTransferOrder]
GO

/****** Object:  StoredProcedure [dbo].[ZWM_GenerateTransferOrder]    Script Date: 01/09/2015 14:42:18 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[ZWM_GenerateTransferOrder] (
	@CoNum			CoNumType
	,@CoLine		CoLineType
	,@CoRelease		CoReleaseType
	,@Item			ItemType
	,@UM			UMType
	,@Qty			QtyUnitNoNegType
	,@WhseFrom		WhseType 
	,@WhseTo		WhseType -- tabla coitem
	,@TransitLoc	LocType
	,@SchRcvDate	DateType
	,@SchShipDate	DateType
	,@Key			LongListType OUTPUT
	,@Infobar		InfobarType OUTPUT
) as


-- Check for existence of Generic External Touch Point routine (this section was generated by SpETPCodeSp and inserted by CallETPs.exe):
   IF OBJECT_ID(N'dbo.EXTGEN_ZWM_GenerateTransferOrder') IS NOT NULL
   BEGIN
      DECLARE @EXTGEN_SpName sysname
      SET @EXTGEN_SpName = N'dbo.EXTGEN_ZWM_GenerateTransferOrder'
      -- Invoke the ETP routine, passing in (and out) this routine's parameters:
      DECLARE @EXTGEN_Severity int
      EXEC @EXTGEN_Severity = @EXTGEN_SpName
		@CoNum
		,@CoLine
		,@CoRelease
		,@Item
		,@UM
		,@Qty
		,@WhseFrom
		,@WhseTo
		,@TransitLoc
		,@SchRcvDate
		,@SchShipDate
		,@Key		OUTPUT
		,@Infobar	OUTPUT	
 
      -- ETP routine can RETURN 1 to signal that the remainder of this standard routine should now proceed:
      IF @EXTGEN_Severity <> 1
         RETURN @EXTGEN_Severity
   END
   -- End of Generic External Touch Point code.
   
DECLARE
@DueDate				DateType
,@Severity				INT
,@CurTrnNum				TrnNumType
,@CurTrnLine			TrnLineType
,@TrnLoc				LocType
,@FOBSite				SiteType
,@ItemLocQuestionAsked  FlagNyType
,@PromptMsg				InfobarType
,@PromptButtons			InfobarType
,@Prefix				LongListType
,@KeyLength				INT
,@Context				LongListType
,@Loc					LocType
,@RecordProcessed		INT
,@Site					SiteType

SELECT @Site = site FROM parms with (readuncommitted) WHERE parm_key = 0

SET @CoNum = dbo.ExpandKyByType('CoNumType',@CoNum)
SELECT @DueDate = due_date FROM coitem WHERE co_num = @CoNum and co_line = @CoLine and co_release = @CoRelease
--SELECT @Prefix = trn_prefix FROM invparms

SELECT @Prefix = prefix_transfer_picklist FROM zwm_parms_mst

SET @KeyLength = 10

BEGIN TRANSACTION

UPDATE coitem SET ref_type = 'T'  where co_num = @CoNum and co_line = @CoLine and co_release = @CoRelease

IF @Key is null
BEGIN
	-- Genera el numero de transferencia
	EXEC @Severity = NextTrnSp
	  @Context      = @Context
	, @Prefix       = @Prefix
	, @KeyLength    = @KeyLength
	, @Key          = @Key OUTPUT
	, @Infobar      = @Infobar OUTPUT
END

IF @Severity <> 0
BEGIN
	ROLLBACK
	RETURN @Severity
END

-- crea, si no existe, la relacion entre el item, whse y loc
  IF (SELECT TOP 1 Loc FROM ItemLoc WHERE ItemLoc.item = @Item and ItemLoc.whse = @WhseTo and ItemLoc.loc = @TransitLoc ) IS NULL
   BEGIN
   EXEC @Severity = [dbo].[ItemWhstkSp]
     @PBegItem = @Item,
     @PEndItem = @Item,
     @PWhse = @WhseTo,
     @PLoc = @TransitLoc,
     @PMrbFlag = 0,
     @PPermFlag = 0,
     @RecordProcessed = @RecordProcessed OUTPUT,
     @Infobar = @Infobar OUTPUT
   END

-- crea, si no existe, la relacion entre el item, whse y loc
  IF (SELECT TOP 1 Loc FROM ItemLoc WHERE ItemLoc.item = @Item and ItemLoc.whse = @WhseFrom and ItemLoc.loc = @TransitLoc ) IS NULL
   BEGIN
   EXEC @Severity = [dbo].[ItemWhstkSp]
     @PBegItem = @Item,
     @PEndItem = @Item,
     @PWhse = @WhseTo,
     @PLoc = @TransitLoc,
     @PMrbFlag = 0,
     @PPermFlag = 0,
     @RecordProcessed = @RecordProcessed OUTPUT,
     @Infobar = @Infobar OUTPUT
   END

IF @Severity <> 0
BEGIN
	ROLLBACK
	RETURN @Severity
END

-- genera la transferencia
EXEC	@Severity = [dbo].[TransAddSp]
		@PTrnNum				= @Key,
		@PItem					= @Item,
		@PFromSite				= @Site,
		@PFromWhse				= @WhseFrom,
		@PToSite				= @Site,
		@PToWhse				= @WhseTo,
		@PQtyOrdered			= @Qty,
		@PDueDate				= @DueDate,
		@PToRefType				= 'O',
		@PToRefNum				= @CoNum,
		@PToRefLineSuf			= @CoLine,
		@PToRefRelease			= @CoRelease,
		@PFromMrpFirm			= NULL,
		@PRcptsRefNum			= NULL,
		@CurTrnNum				= @CurTrnNum OUTPUT,
		@CurTrnLine				= @CurTrnLine OUTPUT,
		@TrnLoc					= NULL,
		@FOBSite				= NULL,
		@ItemLocQuestionAsked	= @ItemLocQuestionAsked OUTPUT,
		@PromptMsg				= @PromptMsg OUTPUT,
		@PromptButtons			= @PromptButtons OUTPUT,
		@Infobar				= @Infobar OUTPUT
		

IF @Severity <> 0
BEGIN
	ROLLBACK
	RETURN @Severity
END
ELSE
	COMMIT

update trnitem set sch_rcv_date = @SchRcvDate, sch_ship_date = @SchShipDate where trn_num = @Key

set @Infobar = 'La transferencia '+@key+' ha sido creada'


RETURN @Severity
GO


