/****** Object:  StoredProcedure [dbo].[ZWM_ValidatePackWorkbenchSp]    Script Date: 01/09/2015 15:01:19 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ZWM_ValidatePackWorkbenchSp]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[ZWM_ValidatePackWorkbenchSp]
GO

/****** Object:  StoredProcedure [dbo].[ZWM_ValidatePackWorkbenchSp]    Script Date: 01/09/2015 15:01:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


--valida que los pickList esten pickeados para una hoja de ruta
CREATE procedure [dbo].[ZWM_ValidatePackWorkbenchSp] (
	@RouteId		ZwmIdRouteMapType
	,@Infobar		InfobarType OUTPUT
)
as


 -- Check for existence of Generic External Touch Point routine (this section was generated by SpETPCodeSp and inserted by CallETPs.exe):
   IF OBJECT_ID(N'dbo.EXTGEN_ZWM_ValidatePackWorkbenchSp') IS NOT NULL
   BEGIN
      DECLARE @EXTGEN_SpName sysname
      SET @EXTGEN_SpName = N'dbo.EXTGEN_ZWM_ValidatePackWorkbenchSp'
      -- Invoke the ETP routine, passing in (and out) this routine's parameters:
      DECLARE @EXTGEN_Severity int
      EXEC @EXTGEN_Severity = @EXTGEN_SpName
		@RouteId		   
		,@Infobar		 OUTPUT
 
      -- ETP routine can RETURN 1 to signal that the remainder of this standard routine should now proceed:
      IF @EXTGEN_Severity <> 1
         RETURN @EXTGEN_Severity
   END
   -- End of Generic External Touch Point code.



Declare @Severity int


IF (SELECT count(pl.pick_list_id) FROM pick_list pl WHERE pl.status = 'O' AND (pl.ZWM_IdRouteMap = @RouteID)) > 0 
BEGIN
	SET @Infobar = 'Hay Pick List en estado "Abierto"'
	SET @Severity = 16
	RETURN @Severity
END
GO


