/****** Object:  StoredProcedure [dbo].[ZWM_DimensionsUnitWeightSp]    Script Date: 01/09/2015 14:39:33 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ZWM_DimensionsUnitWeightSp]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[ZWM_DimensionsUnitWeightSp]
GO

/****** Object:  StoredProcedure [dbo].[ZWM_DimensionsUnitWeightSp]    Script Date: 01/09/2015 14:39:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE PROCEDURE [dbo].[ZWM_DimensionsUnitWeightSp] (
	@Item				ItemType			= NULL
	,@UmStk1			UMType				= NULL
	,@Weight			ZwmVolumeWeightType = NULL
	,@UnitWeight		ZwmVolumeWeightType = NULL OUTPUT
	,@Infobar		    InfobarType			= NULL OUTPUT
)
AS

 -- Check for existence of Generic External Touch Point routine (this section was generated by SpETPCodeSp and inserted by CallETPs.exe):
   IF OBJECT_ID(N'dbo.EXTGEN_ZWM_DimensionsUnitWeightSp') IS NOT NULL
   BEGIN
      DECLARE @EXTGEN_SpName sysname
      SET @EXTGEN_SpName = N'dbo.EXTGEN_ZWM_DimensionsUnitWeightSp'
      -- Invoke the ETP routine, passing in (and out) this routine's parameters:
      DECLARE @EXTGEN_Severity int
      EXEC @EXTGEN_Severity = @EXTGEN_SpName
		@Item		   
		,@UmStk1
		,@Weight	       
		,@UnitWeight	OUTPUT
		,@Infobar		OUTPUT
 
      -- ETP routine can RETURN 1 to signal that the remainder of this standard routine should now proceed:
      IF @EXTGEN_Severity <> 1
         RETURN @EXTGEN_Severity
   END
   -- End of Generic External Touch Point code.
   
DECLARE @Severity int
,@Conv UMConvFactorType

SET @Weight = ISNULL(@Weight,0)

IF @UmStk1 IS NULL
BEGIN
	SET @Infobar = 'Debe incorporar UM Stock 1'
	SET @Severity = 16
	RETURN @Severity
END

SET @Conv = dbo.Getumcf(@UMStk1, @Item,NULL,NULL)
SET @UnitWeight= ROUND(@Weight * @Conv, 10)

RETURN @Severity
GO


