/****** Object:  StoredProcedure [dbo].[ZWM_RFErrorSp]    Script Date: 01/20/2015 15:12:44 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ZWM_RFErrorSp]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[ZWM_RFErrorSp]
GO

/****** Object:  StoredProcedure [dbo].[ZWM_RFErrorSp]    Script Date: 01/20/2015 15:12:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[ZWM_RFErrorSp](
     @Infobar		 InfobarType = NULL OUTPUT
)
AS

   -- Check for existence of Generic External Touch Point routine (this section was generated by SpETPCodeSp and inserted by CallETPs.exe):
   IF OBJECT_ID(N'dbo.EXTGEN_ZWM_RFErrorSp') IS NOT NULL
   BEGIN
      DECLARE @EXTGEN_SpName sysname
      SET @EXTGEN_SpName = N'dbo.EXTGEN_ZWM_RFErrorSp'
      -- Invoke the ETP routine, passing in (and out) this routine's parameters:
      DECLARE @EXTGEN_Severity int
      EXEC @EXTGEN_Severity = @EXTGEN_SpName
			@Infobar OUTPUT
 
      -- ETP routine can RETURN 1 to signal that the remainder of this standard routine should now proceed:
      IF @EXTGEN_Severity <> 1
         RETURN @EXTGEN_Severity
   END
   -- End of Generic External Touch Point code.

Declare @Severity int

SET @Severity = 16
SET @Infobar = 'Error: revisar parametros de Almacenamiento y RF'
RETURN @Severity
GO


