-------------------------------------------------------------------------------
-- SQL Script generated by FormSync 9.1.0.9 As of 10/10/2014 05:09 p.m.
-- Source Configuration: BAR_Forms
-- Objects Scripted:
--   PropertyDefaults - Property Class Extension: ZWM_Route
-------------------------------------------------------------------------------
DECLARE @FormID int
DELETE FROM PropertyDefaults WHERE [PropertyName] = N'ZWM_Route' AND [IsPropertyClassExtension] = 1 AND [ScopeType] = 0  AND [ScopeName] = N'[NULL]' 

DELETE FROM PropertyDefaultDragDropEvents WHERE [PropertyName] = N'ZWM_Route' AND [IsPropertyClassExtension] = 1 AND [ScopeType] = 0  AND [ScopeName] = N'[NULL]' 

INSERT INTO PropertyDefaults ( 
 [PropertyName], [ScopeType], [ScopeName], 
 [Description], [Label], [ListSource], 
 [FindFromForm], [FindFromProperty], [MaintainFromSpec], 
 [Validators], [MaxCharacters], [ValidateImmediately], [ValueIsListIndex], 
 [LockedBy], [DataType], [IsPropertyClassExtension], [Flags], [ComponentFlags], 
 [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], 
 [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
 [Post301DataType], [Post301Format] ) 
VALUES ( 
 N'ZWM_Route', 0, N'[NULL]', 
 NULL, NULL, NULL, 
 N'ZWM_Routes', N'Route', N'ZWM_Routes', 
 NULL, 0, 0, 0, 
 NULL, NULL, 1, 0, 0, 
 NULL, NULL, NULL, NULL, 
 NULL, NULL, 0, N'StdDetailsAddFind', 
 NULL, N'AUTOIME(NoControl)' ) 


