-------------------------------------------------------------------------------
-- SQL Script generated by FormSync 9.1.0.9 As of 09/01/2015 15:30
-- Source Configuration: ZLA_Dev_Forms
-- Objects Scripted:
--   Form: ZWM_ShipConfirmation 
--      Components: ChangeWarehouseObjMenu, CustNumGridCol, CustSeqGridCol, DeselectAllButton,
--         FormCollectionGrid, FormCurWhseVarEdit, FormCurWhseVarStatic, GotoActivitiesFolderToolbarButton,
--         GotoFilesFolderToolbarButton, GotoMaintenanceFolderToolbarButton, GotoQueriesFolderToolbarButton,
--         GotoReportsFolderToolbarButton, GotoUtilitiesFolderToolbarButton, GridGroupBox,
--         IgnoreCount, IgnoreLCR, LocGridCol, OnHandNegVarCheckBox, OptionsGroupBox,
--         PackagesGridCol, SelectAllButton, ShipButton, ShipmentGridCol, StatusGridCol,
--         TransDateStatic, TransDateVarEdit, UbSelectGridCol, WeightGridCol, WhseGridCol,
--         ZlaShipNum, ZwmRefType, ZwmRouteIdComboBox, ZwmRouteIdStatic, ZwmShipTransferBtn
--      Event Handlers: CallShipConfirmation(0), ChangeWarehouse(0), ChangeWarehouse(1),
--         ChangeWarehouse(2), DeselectAll(0), GoToActivitiesFolder(0), GoToFilesFolder(0),
--         GoToMaintenanceFolder(0), GoToQueriesFolder(0), GoToReportsFolder(0), GoToUtilitiesFolder(0),
--         LaunchChangeWarehouse(0), SelectAll(0), Ship(0), Ship(1), Ship(2), Ship(3),
--         Ship(4), Ship(5), Ship(6), Ship(7), Ship(8), StdFormCalledFormReturned(0),
--         StdFormClose(0), StdFormFilterInPlaceExecuteCompleted(0), StdFormFilterInPlaceExecuteCompleted(1),
--         StdFormPredisplay(0), StdFormPredisplay(1), ZwmGetRefType(0), ZwmShipTransfer(0),
--         ZwmShipTransfer(1), ZwmShipTransfer(2), ZwmShipTransfer(3), ZwmShipTransfer(4),
--         ZwmShipTransfer(5), ZwmShowHideBtns(0)
--      Variables: cvw_ShipButton, cvw_ZwmShipTransferBtn, fds_DataSource, fds_SC2,
--         InitialCommand
--      ActiveXScripts: ZWM_ShipConfirmation
-------------------------------------------------------------------------------
DECLARE @FormID int
SET @FormID = NULL
SELECT @FormID = Forms.ID FROM Forms WHERE [Name] = N'ZWM_ShipConfirmation' AND [ScopeType] = 1
IF @FormID IS NOT NULL
BEGIN
   DELETE FROM Forms WHERE ID = @FormID
   DELETE FROM FormEventHandlers WHERE FormID = @FormID
   DELETE FROM FormComponents WHERE FormID = @FormID
   DELETE FROM ActiveXComponentProperties WHERE FormID = @FormID
   DELETE FROM Variables WHERE FormID = @FormID
   DELETE FROM FormComponentDragDropEvents WHERE FormID = @FormID
   DELETE FROM DerivedFormOverrides WHERE FormID = @FormID
END
INSERT INTO [Forms] (
  [ScopeType], [ScopeName], [Component], [Name], [SubComponent], [Type], [Caption], 
  [PrimaryDataSource], 
  [StandardOperations], [TopPos], [LeftPos], [Height], [Width], [IconFileName], [HelpFileName], [HelpContextID], [Flags], [LockedBy], 
  [FilterFormSpec], [PaneZeroSize], [Description], [MasterDeviceID], [BaseFormName] ) 
VALUES ( 
  1, N'[NULL]', NULL, N'ZWM_ShipConfirmation', NULL, 1, N'fShipConfirmation', 
  N'V(fds_DataSource)', 
  160, CAST('0' AS float), CAST('0' AS float), CAST('30' AS float), CAST('87' AS float), NULL, N'default.html?helpcontent=mergedProjects/sl_custvend/forms/cotopics/ship_confirmation.htm', -1, 968, N'sa', 
  NULL, N'0', NULL, 0, NULL)
SELECT @FormID = Forms.ID FROM Forms WHERE [Name] = N'ZWM_ShipConfirmation' AND [ScopeType] = 1
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'ChangeWarehouseObjMenu', -1, 
  0, 10, CAST('0' AS float), CAST('0' AS float), CAST('0' AS float), CAST('0' AS float), CAST('0' AS float), N'sChange&Warehouse', 
  NULL, 
  NULL, 0, NULL, 
  0, N'LaunchChangeWarehouse', NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 0, 0, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, NULL, 
  NULL, N'AUTOIME(NoControl)', 
  NULL, N'sChange&Warehouse')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'CustNumGridCol', -1, 
  3, 15, CAST('6.5999999999999996' AS float), CAST('28.714285714285715' AS float), CAST('6.666666666666667' AS float), CAST('0' AS float), CAST('10.428571428571429' AS float), N'sCustomer', 
  NULL, 
  N'FormCollectionGrid', 3, N'object.CustNum', 
  1, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 1, 0, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', N'CustNumVar()', NULL, NULL, N'CustNum', 
  NULL, N'AUTOIME(NoControl)', 
  NULL, N'sCustomer')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'CustSeqGridCol', -1, 
  4, 15, CAST('6.5999999999999996' AS float), CAST('39.142857142857146' AS float), CAST('6.666666666666667' AS float), CAST('0' AS float), CAST('6.8571428571428568' AS float), N'sShipTo', 
  NULL, 
  N'FormCollectionGrid', 4, N'object.CustSeq', 
  1, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 1, 0, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, N'CustSeq', 
  NULL, N'AUTOIME(NoControl)', 
  NULL, N'sShipTo')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'DeselectAllButton', -1, 
  10, 8, CAST('4.7999999999999998' AS float), CAST('17.857142857142858' AS float), CAST('1.3999999999999999' AS float), CAST('0' AS float), CAST('15' AS float), N'sDese&lectAll', 
  NULL, 
  NULL, 0, NULL, 
  0, N'DeselectAll', NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 0, 0, NULL, NULL, N'default.html?helpcontent=mergedProjects/core/buttons/d/deselect_all_button.htm', -1, N'StdDefault', 
  NULL, NULL, NULL, 
  N'0', N'Button()', NULL, NULL, NULL, 
  NULL, N'BTF() AUTOIME(NoControl)', 
  NULL, N'sDese&lectAll')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'FormCollectionGrid', -1, 
  12, 14, CAST('6.5999999999999996' AS float), CAST('1.8571428571428572' AS float), CAST('14.800000000000001' AS float), CAST('2' AS float), CAST('83.428571428571431' AS float), NULL, 
  NULL, 
  NULL, 0, N'objects', 
  3, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 0, 0, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', N'StdGrid()', NULL, NULL, NULL, 
  NULL, N'AUTOIME(NoControl)', 
  NULL, NULL)
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'FormCurWhseVarEdit', -1, 
  2, 27, CAST('0.8666666666666667' AS float), CAST('9.7142857142857135' AS float), CAST('1.3' AS float), CAST('0' AS float), CAST('9' AS float), NULL, 
  NULL, 
  NULL, 0, N'variables.FormCurWhse', 
  6, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  4096, NULL, 1, 0, NULL, NULL, N'default.html?helpcontent=mergedProjects/sl_custvend/fields/w/whse_ship_confirmation.htm', -1, NULL, 
  NULL, NULL, NULL, 
  N'0', N'WhseVar()', NULL, NULL, NULL, 
  NULL, N'AUTOIME(NoControl)', 
  NULL, N'sWhse')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'FormCurWhseVarStatic', -1, 
  1, 0, CAST('1.0666666666666667' AS float), CAST('2.5714285714285716' AS float), CAST('1' AS float), CAST('0' AS float), CAST('6.5714285714285712' AS float), N'sWhse', 
  NULL, 
  NULL, 0, NULL, 
  0, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 0, 0, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, NULL, 
  NULL, N'AUTOIME(NoControl) JUSTIFY(R)', 
  NULL, N'sWhse')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'GotoActivitiesFolderToolbarButton', -1, 
  0, 11, CAST('0' AS float), CAST('0' AS float), CAST('0' AS float), CAST('0' AS float), CAST('0' AS float), N'sGoToActivitiesFolder', 
  NULL, 
  NULL, 0, NULL, 
  0, N'GoToActivitiesFolder', NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 0, 0, N'GotoActivities.png', NULL, N'default.html?helpcontent=mergedProjects/sl_main/buttons/g/gotoactivitiesfoldertoolbarbutton.htm', -1, NULL, 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, NULL, 
  NULL, N'AUTOIME(NoControl)', 
  NULL, N'sGoToActivitiesFolder')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'GotoFilesFolderToolbarButton', -1, 
  0, 11, CAST('0' AS float), CAST('0' AS float), CAST('0' AS float), CAST('0' AS float), CAST('0' AS float), N'sGoToFilesFolder', 
  NULL, 
  NULL, 0, NULL, 
  0, N'GoToFilesFolder', NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 0, 0, N'GotoFiles.png', NULL, N'default.html?helpcontent=mergedProjects/sl_main/buttons/g/gotofilesfoldertoolbarbutton.htm', -1, NULL, 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, NULL, 
  NULL, N'AUTOIME(NoControl)', 
  NULL, N'sGoToFilesFolder')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'GotoMaintenanceFolderToolbarButton', -1, 
  0, 11, CAST('0' AS float), CAST('0' AS float), CAST('0' AS float), CAST('0' AS float), CAST('0' AS float), N'sGoToMaintenanceFolder', 
  NULL, 
  NULL, 0, NULL, 
  0, N'GoToMaintenanceFolder', NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 0, 0, N'GotoMaintenance.png', NULL, N'default.html?helpcontent=mergedProjects/sl_main/buttons/g/gotomaintenancefoldertoolbarbutton.htm', -1, NULL, 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, NULL, 
  NULL, N'AUTOIME(NoControl)', 
  NULL, N'sGoToMaintenanceFolder')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'GotoQueriesFolderToolbarButton', -1, 
  0, 11, CAST('0' AS float), CAST('0' AS float), CAST('0' AS float), CAST('0' AS float), CAST('0' AS float), N'sGoToQueriesFolder', 
  NULL, 
  NULL, 0, NULL, 
  0, N'GoToQueriesFolder', NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 0, 0, N'GotoQueries.png', NULL, N'default.html?helpcontent=mergedProjects/sl_main/buttons/g/gotoqueriesfoldertoolbarbutton.htm', -1, NULL, 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, NULL, 
  NULL, N'AUTOIME(NoControl)', 
  NULL, N'sGoToQueriesFolder')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'GotoReportsFolderToolbarButton', -1, 
  0, 11, CAST('0' AS float), CAST('0' AS float), CAST('0' AS float), CAST('0' AS float), CAST('0' AS float), N'sGoToReportsFolder', 
  NULL, 
  NULL, 0, NULL, 
  0, N'GoToReportsFolder', NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 0, 0, N'GotoReports.png', NULL, N'default.html?helpcontent=mergedProjects/sl_main/buttons/g/gotoreportsfoldertoolbarbutton.htm', -1, NULL, 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, NULL, 
  NULL, N'AUTOIME(NoControl)', 
  NULL, N'sGoToReportsFolder')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'GotoUtilitiesFolderToolbarButton', -1, 
  0, 11, CAST('0' AS float), CAST('0' AS float), CAST('0' AS float), CAST('0' AS float), CAST('0' AS float), N'sGoToUtilitiesFolder', 
  NULL, 
  NULL, 0, NULL, 
  0, N'GoToUtilitiesFolder', NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 0, 0, N'GotoUtilities.png', NULL, N'default.html?helpcontent=mergedProjects/sl_main/buttons/g/gotoutilitiesfoldertoolbarbutton.htm', -1, NULL, 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, NULL, 
  NULL, N'AUTOIME(NoControl)', 
  NULL, N'sGoToUtilitiesFolder')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'GridGroupBox', -1, 
  8, 6, CAST('3.7000000000000002' AS float), CAST('0.8571428571428571' AS float), CAST('18.133333333333333' AS float), CAST('0' AS float), CAST('85.571428571428569' AS float), NULL, 
  NULL, 
  NULL, 0, NULL, 
  0, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 0, 0, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', N'StdGroupBox()', NULL, NULL, NULL, 
  NULL, N'AUTOIME(NoControl)', 
  NULL, NULL)
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'IgnoreCount', -1, 
  5, 5, CAST('2.3999999999999999' AS float), CAST('9.7142857142857135' AS float), CAST('1' AS float), CAST('0' AS float), CAST('23' AS float), N'sIgnoreCycleCountWarning', 
  NULL, 
  NULL, 0, N'variables.IgnoreCountVar(INITIALVALUE(0))', 
  6, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  4096, NULL, 0, 0, NULL, NULL, N'default.html?helpcontent=mergedProjects/sl_custvend/fields/i/ignore_lcr_warning_ship_confirmation.htm', -1, NULL, 
  NULL, NULL, NULL, 
  N'0', N'BooleanVar()', NULL, NULL, NULL, 
  NULL, N'BTF() AUTOIME(NoControl)', 
  NULL, N'sIgnoreCycleCountWarning')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'IgnoreLCR', -1, 
  6, 5, CAST('2.3999999999999999' AS float), CAST('36.571428571428569' AS float), CAST('1' AS float), CAST('0' AS float), CAST('18' AS float), N'sIgnoreLCRWarning', 
  NULL, 
  NULL, 0, N'variables.IgnoreLCRVar(INITIALVALUE(0))', 
  6, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  4096, NULL, 0, 0, NULL, NULL, N'default.html?helpcontent=mergedProjects/sl_custvend/fields/i/ignore_lcr_warning_ship_confirmation.htm', -1, NULL, 
  NULL, NULL, NULL, 
  N'0', N'BooleanVar()', NULL, NULL, NULL, 
  NULL, N'BTF() AUTOIME(NoControl)', 
  NULL, N'sIgnoreLCRWarning')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'LocGridCol', -1, 
  9, 15, CAST('6.5999999999999996' AS float), CAST('84.142857142857139' AS float), CAST('6.666666666666667' AS float), CAST('0' AS float), CAST('17' AS float), N'sLocation', 
  NULL, 
  N'FormCollectionGrid', 9, N'object.ShipLoc', 
  1, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 1, 0, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', N'Location()', NULL, NULL, N'Loc', 
  NULL, N'AUTOIME(NoControl)', 
  NULL, N'sLocation')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'OnHandNegVarCheckBox', -1, 
  7, 5, CAST('2.3999999999999999' AS float), CAST('60' AS float), CAST('1' AS float), CAST('0' AS float), CAST('18.428571428571427' AS float), N'sOnHandNegative', 
  NULL, 
  NULL, 0, N'variables.LocalNegFlagVar', 
  6, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  4096, NULL, 0, 0, NULL, NULL, N'default.html?helpcontent=mergedProjects/sl_custvend/fields/o/on_hand_negative_ship_confirmation.htm', -1, NULL, 
  NULL, NULL, NULL, 
  N'0', N'BooleanVar()', NULL, NULL, NULL, 
  NULL, N'AUTOIME(NoControl)', 
  NULL, N'sOnHandNegative')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'OptionsGroupBox', -1, 
  0, 6, CAST('0.066666666666666666' AS float), CAST('0.8571428571428571' AS float), CAST('3.8999999999999999' AS float), CAST('0' AS float), CAST('85.571428571428569' AS float), NULL, 
  NULL, 
  NULL, 0, NULL, 
  0, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 0, 0, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', N'StdGroupBox()', NULL, NULL, NULL, 
  NULL, N'AUTOIME(NoControl)', 
  NULL, NULL)
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'PackagesGridCol', -1, 
  6, 15, CAST('6.5999999999999996' AS float), CAST('57.428571428571431' AS float), CAST('6.666666666666667' AS float), CAST('0' AS float), CAST('10' AS float), N's#Packages', 
  NULL, 
  N'FormCollectionGrid', 6, N'object.QtyPackages', 
  1, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 1, 0, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, N'Packages', 
  NULL, N'AUTOIME(NoControl)', 
  NULL, N's#Packages')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'SelectAllButton', -1, 
  9, 8, CAST('4.7999999999999998' AS float), CAST('2.1428571428571428' AS float), CAST('1.3999999999999999' AS float), CAST('0' AS float), CAST('15' AS float), N'sSelec&tAll', 
  NULL, 
  NULL, 0, NULL, 
  0, N'SelectAll', NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 0, 0, NULL, NULL, N'default.html?helpcontent=mergedProjects/core/buttons/s/select_all_button.htm', -1, N'StdDefault', 
  NULL, NULL, NULL, 
  N'0', N'Button()', NULL, NULL, NULL, 
  NULL, N'BTF() AUTOIME(NoControl)', 
  NULL, N'sSelec&tAll')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'ShipButton', -1, 
  11, 8, CAST('4.7999999999999998' AS float), CAST('33.75' AS float), CAST('1.3999999999999999' AS float), CAST('0' AS float), CAST('15' AS float), N'sS&hip', 
  NULL, 
  NULL, 0, NULL, 
  0, N'Ship', NULL, NULL, NULL, NULL, 
  NULL, 
  4096, NULL, 0, 0, NULL, NULL, N'default.html?helpcontent=mergedProjects/sl_custvend/buttons/s/ship_button_ship_confirmation.htm', -1, NULL, 
  NULL, NULL, NULL, 
  N'0', N'Button()', NULL, NULL, NULL, 
  NULL, N'BTF() AUTOIME(NoControl)', 
  NULL, N'sS&hip')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'ShipmentGridCol', -1, 
  2, 15, CAST('6.5999999999999996' AS float), CAST('12' AS float), CAST('6.666666666666667' AS float), CAST('0' AS float), CAST('16.714285714285715' AS float), N'sShipment', 
  NULL, 
  N'FormCollectionGrid', 1, N'object.ShipmentId', 
  1, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 1, 0, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', N'ShipmentStatusVar(R)', NULL, NULL, N'ShipmentID', 
  NULL, N'AUTOIME(NoControl)', 
  NULL, N'sShipment')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'StatusGridCol', -1, 
  5, 15, CAST('6.5999999999999996' AS float), CAST('46' AS float), CAST('6.666666666666667' AS float), CAST('0' AS float), CAST('11.428571428571429' AS float), N'sStatus', 
  NULL, 
  N'FormCollectionGrid', 5, N'object.Status', 
  1, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  1052672, NULL, 1, 0, NULL, NULL, NULL, 0, N'StdDefault', 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, N'ShipmentStatus', 
  N'LENGTH(10)', N'AUTOIME(NoControl)', 
  NULL, N'sStatus')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'TransDateStatic', -1, 
  3, 0, CAST('1.0666666666666667' AS float), CAST('22.571428571428573' AS float), CAST('1' AS float), CAST('0' AS float), CAST('13.571428571428571' AS float), N'sTransactionDate', 
  NULL, 
  NULL, 0, NULL, 
  0, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 0, 0, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, NULL, 
  NULL, N'AUTOIME(NoControl) JUSTIFY(R)', 
  NULL, N'sTransactionDate')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'TransDateVarEdit', -1, 
  4, 26, CAST('0.8666666666666667' AS float), CAST('36.571428571428569' AS float), CAST('1.3' AS float), CAST('0' AS float), CAST('13' AS float), NULL, 
  N'DateForAcctPeriod(TransDateVarEdit, TransDateStatic, @%update),Ask(DateChkPromptMsg,DateChkPromptButtons,),TransDateValidate', 
  NULL, 0, N'variables.TransDateVar(INITIALVALUE(CURDATE()))', 
  6, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  4096, N'CURDATE()', 0, 0, NULL, NULL, N'default.html?helpcontent=mergedProjects/sl_custvend/fields/t/transaction_date_ship_confirmation.htm', -1, NULL, 
  NULL, NULL, NULL, 
  N'0', N'DateVar()', NULL, NULL, NULL, 
  N'DEFAULTVALUE(CURDATE())', N'AUTOIME(NoControl)', 
  NULL, NULL)
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'UbSelectGridCol', -1, 
  1, 15, CAST('6.5999999999999996' AS float), CAST('6' AS float), CAST('6.666666666666667' AS float), CAST('0' AS float), CAST('6' AS float), N'sSelect', 
  NULL, 
  N'FormCollectionGrid', 0, N'object.UbSelect', 
  1, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  4168, NULL, 0, 0, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', N'BooleanVar()', NULL, NULL, N'ListYesNo', 
  NULL, N'AUTOIME(NoControl)', 
  NULL, N'sSelect')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'WeightGridCol', -1, 
  7, 15, CAST('6.5999999999999996' AS float), CAST('67.428571428571431' AS float), CAST('6.666666666666667' AS float), CAST('0' AS float), CAST('10.714285714285714' AS float), N'sTotWeight', 
  NULL, 
  N'FormCollectionGrid', 7, N'object.Weight', 
  1, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 1, 0, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, N'TotalWeight', 
  NULL, N'AUTOIME(NoControl)', 
  NULL, N'sTotWeight')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'WhseGridCol', -1, 
  8, 15, CAST('6.5999999999999996' AS float), CAST('78.142857142857139' AS float), CAST('6.666666666666667' AS float), CAST('0' AS float), CAST('6' AS float), N'sWhse', 
  NULL, 
  N'FormCollectionGrid', 8, N'object.Whse', 
  1, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  4096, NULL, 1, 0, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', N'Whse()', NULL, NULL, N'Whse', 
  NULL, N'AUTOIME(NoControl)', 
  NULL, N'sWhse')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'ZlaShipNum', -1, 
  0, 15, CAST('0' AS float), CAST('0' AS float), CAST('7.6923076923076925' AS float), CAST('0' AS float), CAST('16.666666666666668' AS float), N'sZwmShipNum', 
  NULL, 
  N'FormCollectionGrid', 2, N'object.ZlaShipNum', 
  1, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 0, 0, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, NULL, 
  NULL, N'AUTOIME(NoControl)', 
  NULL, N'sZwmShipNum')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'ZwmRefType', -1, 
  0, 1, CAST('2.3076923076923075' AS float), CAST('81.333333333333329' AS float), CAST('1.3076923076923077' AS float), CAST('0' AS float), CAST('2.5' AS float), NULL, 
  NULL, 
  NULL, 0, N'variables.ZwmRefType', 
  6, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 0, 1, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, NULL, 
  NULL, N'AUTOIME(NoControl)', 
  NULL, NULL)
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'ZwmRouteIdComboBox', -1, 
  0, 27, CAST('0.8666666666666667' AS float), CAST('69.5' AS float), CAST('1.2307692307692308' AS float), CAST('0' AS float), CAST('15.333333333333334' AS float), NULL, 
  NULL, 
  NULL, 0, N'variables.ZwmRouteId', 
  6, NULL, NULL, NULL, NULL, NULL, 
  N'STDOLE ZWM_PickList(  PROPERTIES(ZwmIdRouteMap, ZwmRefType, Status, CreateDate, ZwmDerRefType) DISPLAY(1,3,5)DISTINCT() FILTER(ZwmIdRouteMap <> '''' and Status = ''A'')ORDERBY(CreateDate desc and ZwmIdRouteMap asc))', 
  0, NULL, 1, 0, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, NULL, 
  NULL, N'AUTOIME(NoControl)', 
  NULL, NULL)
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'ZwmRouteIdStatic', -1, 
  0, 0, CAST('1.0769230769230769' AS float), CAST('51.666666666666664' AS float), CAST('1' AS float), CAST('0' AS float), CAST('17.5' AS float), N'sZwmRouteId', 
  NULL, 
  NULL, 0, NULL, 
  0, NULL, NULL, NULL, NULL, NULL, 
  NULL, 
  0, NULL, 0, 0, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, NULL, 
  NULL, N'AUTOIME(NoControl) JUSTIFY(R)', 
  NULL, N'sZwmRouteId')
INSERT INTO FormComponents (
  [FormID], [Name], [DeviceID], 
  [TabOrder], [Type], [TopPos], [LeftPos],[Height], [ListHeight], [Width], [Caption], 
  [Validators], 
  [ContainerName], [ContainerSequence], [DataSource], 
  [Binding], [EventToGenerate], [SelectionEventToGenerate], [LoseFocusEventToGenerate], [GainFocusEventToGenerate], [RadioButtonSelectedValue], 
  [ComboListSource], 
  [Flags], [DefaultData], [ReadOnly], [Hidden], [BitmapFileName], [HelpString], [HelpFileName], [HelpContextID], [MenuName], 
  [Format], [FindFromSpec], [MaintainFromSpec], 
  [MaxCharacters], [DefaultFrom], [DataType], [ActiveXControlName], [PropertyClassName], 
  [Post301DataType], [Post301Format], 
  [Description], [EffectiveCaption] )
VALUES (
  @FormID, N'ZwmShipTransferBtn', -1, 
  0, 8, CAST('4.7999999999999998' AS float), CAST('33.75' AS float), CAST('1.3999999999999999' AS float), CAST('0' AS float), CAST('15' AS float), N'sZwmShipTrn', 
  NULL, 
  NULL, 0, NULL, 
  0, N'ZwmShipTransfer', NULL, NULL, NULL, NULL, 
  NULL, 
  4096, NULL, 0, 1, NULL, NULL, NULL, 0, NULL, 
  NULL, NULL, NULL, 
  N'0', NULL, NULL, NULL, NULL, 
  NULL, N'BTF() AUTOIME(NoControl)', 
  NULL, N'sZwmShipTrn')
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'CallShipConfirmation', 0, 0, N'SL.SLShipments.ShipConfirmationSp( PARMS(VAR P(ShipmentId), VAR V(TransDateVar), VAR V(IgnoreLCRVar), VAR V(IgnoreCountVar), MESSAGE) ERRORMESSAGE(mBackEndMessage) SUCCESSMESSAGE(mBackEndMessage) )', NULL, NULL, NULL )
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'ChangeWarehouse', 0, 0, N'SL.SLWhses.CheckWhsePhyInvFlgSp( PARMS(VAR V(FormCurWhse), VAR V(Parm_Site), RVAR V(WhsePhyInvFlg), MESSAGE) ERRORMESSAGE(mBackEndMessage) IGNOREFAILURE() )', NULL, NULL, NULL )
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'ChangeWarehouse', 1, 35, N'VerifyOnlyInstanceAndChangeFormCaption()', NULL, NULL, NULL )
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'ChangeWarehouse', 2, 21, N'StdFormRefresh', NULL, NULL, NULL )
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'DeselectAll', 0, 35, N'DeselectAll', NULL, NULL, NULL )
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'GoToActivitiesFolder', 0, 41, N'MASTER/xModules/xCustomer/xPickPackShip/xActivities', NULL, NULL, NULL )
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'GoToFilesFolder', 0, 41, N'MASTER/xModules/xCustomer/xPickPackShip/xFiles', NULL, NULL, NULL )
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'GoToMaintenanceFolder', 0, 41, N'MASTER/xModules/xCustomer/xPickPackShip', NULL, NULL, NULL )
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'GoToQueriesFolder', 0, 41, N'MASTER/xModules/xCustomer/xPickPackShip/xQueries', NULL, NULL, NULL )
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'GoToReportsFolder', 0, 41, N'MASTER/xModules/xCustomer/xPickPackShip/xReports', NULL, NULL, NULL )
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'GoToUtilitiesFolder', 0, 41, N'MASTER/xModules/xCustomer/xPickPackShip/xUtilities', NULL, NULL, NULL )
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'LaunchChangeWarehouse', 0, 3, N'ChangeWarehouse( )', NULL, NULL, NULL )
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'SelectAll', 0, 35, N'SelectAll', NULL, NULL, NULL )
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'Ship', 0, 0, N'SL.SLPeriods.DateChkSp( PARMS(VAR C(TransDateVarEdit), BSTR C(TransDateStatic), BSTR @%update, MESSAGE, RVAR V(DateChkPromptMsg), RVAR V(DateChkPromptButtons)) ERRORMESSAGE(mBackEndMessage) )', NULL, NULL, NULL )
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'Ship', 1, 35, N'CheckSelected()', NULL, NULL, NULL )
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'Ship', 2, 21, N'StdFormSave', NULL, NULL, NULL )
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'Ship', 3, 35, N'PreShip()', NULL, NULL, NULL )
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'Ship', 4, 0, N'SL.SLCoitemShps.COShippingLoopSp( PARMS(VAR V(LocalNegFlagVar), RVAR V(FirstSequenceWithError), RVAR V(RecordsPosted), RVAR V(PromptMsg), RVAR V(PromptButtons)) ERRORMESSAGE(mBackEndMessage) IGNOREFAILURE() )', NULL, NULL, NULL )
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'Ship', 5, 8, N'Ask(PromptMsg, PromptButtons, PromptResponse)', NULL, NULL, NULL )
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'Ship', 6, 0, N'SL.SLCoitemShps.COShippingCleanupSp( PARMS() )', NULL, NULL, NULL )
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'Ship', 7, 35, N'PostShipEval()', NULL, NULL, NULL )
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'Ship', 8, 21, N'StdFormRefresh(  )', NULL, NULL, NULL )
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'StdFormCalledFormReturned', 0, 35, N'StdFormCalledFormReturned()', NULL, NULL, NULL )
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'StdFormClose', 0, 0, N'SL.SLCoitemShps.COShippingCleanupSp( PARMS() )', NULL, NULL, NULL )
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'StdFormFilterInPlaceExecuteCompleted', 0, 21, N'ZwmGetRefType(  )', NULL, NULL, NULL )
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'StdFormFilterInPlaceExecuteCompleted', 1, 21, N'ZwmShowHideBtns(  )', NULL, NULL, NULL )
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'StdFormPredisplay', 0, 0, N'SL.SLInvparms.GetInvParmsSp ( PARMS(RVAR, RVAR, RVAR V(LocalNegFlagVar), RVAR V(FormCurWhse), RVAR, RVAR, RVAR, RVAR) ERRORMESSAGE(mBackEndMessage) )', NULL, NULL, NULL )
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'StdFormPredisplay', 1, 35, N'VerifyOnlyInstanceAndChangeFormCaption()', NULL, NULL, NULL )
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'ZwmGetRefType', 0, 0, N'SP!.ZWM_GetRefTypeByRouteSheetSp( PARMS(VAR C(ZwmRouteIdComboBox), RVAR V(ZwmRefType), MESSAGE) ERRORMESSAGE(mBackEndMessage) )', NULL, NULL, NULL )
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'ZwmShipTransfer', 0, 0, N'SL.SLPeriods.DateChkSp( PARMS(VAR C(TransDateVarEdit), BSTR C(TransDateStatic), BSTR @%update, MESSAGE, RVAR V(DateChkPromptMsg), RVAR V(DateChkPromptButtons)) ERRORMESSAGE(mBackEndMessage) )', NULL, NULL, NULL )
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'ZwmShipTransfer', 1, 35, N'CheckSelected()', NULL, NULL, NULL )
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'ZwmShipTransfer', 2, 21, N'StdFormSave(  )', NULL, NULL, NULL )
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'ZwmShipTransfer', 3, 35, N'PreShip()', NULL, NULL, NULL )
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'ZwmShipTransfer', 4, 0, N'ZWM_SLShipments.ZWM_TransferOrderShipConfirmationSp( PARMS(VAR P(ShipmentId), MESSAGE) ERRORMESSAGE(mBackEndMessage) SUCCESSMESSAGE(mBackEndMessage) )', NULL, NULL, NULL )
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'ZwmShipTransfer', 5, 21, N'StdFormRefresh(  )', NULL, NULL, NULL )
INSERT INTO FormEventHandlers ( [FormID], [EventName], [Sequence], [ResponseType], [Response], [Response2], [Response3], [Description] ) 
VALUES ( @FormID, N'ZwmShowHideBtns', 0, 35, N'ShowHideButtons()', NULL, NULL, NULL )
INSERT INTO Variables ( [FormID], [Name], [ScopeType], [ScopeName], [Value], [Value2], [Value3], [LockedBy], [Description] ) 
VALUES (@FormID, N'cvw_ShipButton', 1, N'[NULL]', N'Visible:#C(ZwmShipTransferBtn), #C(ZwmRefType) = ''O'', "True"', NULL, NULL, NULL, NULL)
INSERT INTO Variables ( [FormID], [Name], [ScopeType], [ScopeName], [Value], [Value2], [Value3], [LockedBy], [Description] ) 
VALUES (@FormID, N'cvw_ZwmShipTransferBtn', 1, N'[NULL]', N'Visible:#C(ZwmShipTransferBtn), #C(ZwmRefType) = ''T'', "True"', NULL, NULL, NULL, NULL)
INSERT INTO Variables ( [FormID], [Name], [ScopeType], [ScopeName], [Value], [Value2], [Value3], [LockedBy], [Description] ) 
VALUES (@FormID, N'fds_DataSource', 1, N'[NULL]', N'SL.SLShipments( FILTERPERM(Whse=FV(FormCurWhse) and Status=''R'' and ZwmRouteSheet=FV(ZwmRouteId)) )', NULL, NULL, NULL, NULL)
INSERT INTO Variables ( [FormID], [Name], [ScopeType], [ScopeName], [Value], [Value2], [Value3], [LockedBy], [Description] ) 
VALUES (@FormID, N'fds_SC2', 1, N'[NULL]', N'OBJECT2( SL.SLCoShips( CA() ) )', NULL, NULL, NULL, NULL)
INSERT INTO Variables ( [FormID], [Name], [ScopeType], [ScopeName], [Value], [Value2], [Value3], [LockedBy], [Description] ) 
VALUES (@FormID, N'InitialCommand', 1, N'[NULL]', N'FilterInPlace', NULL, NULL, NULL, NULL)
DELETE FROM ActiveXScriptLines WHERE ScriptName = N'ZWM_ShipConfirmation' AND [ScopeType] = 1
DELETE FROM ActiveXScripts WHERE Name = N'ZWM_ShipConfirmation' AND [ScopeType] = 1
INSERT INTO ActiveXScripts ([Name], [ScopeType], [ScopeName], [LockedBy], [Language]) VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', NULL, N'Visual Basic')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 0, N'Option Explicit On')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 1, N'Option Strict On')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 2, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 3, N'Imports System')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 4, N'Imports Microsoft.VisualBasic')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 5, N'Imports Mongoose.IDO.Protocol')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 6, N'Imports Mongoose.Scripting')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 7, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 8, N'Namespace SyteLine.FormScripts')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 9, N'Public Class ZWM_ShipConfirmation')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 10, N'Inherits FormScript')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 11, N'        Sub PostShipEval()')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 12, N'            '' Give user message of number of records posted')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 13, N'            ThisForm.CallGlobalScript("MsgApp", _')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 14, N'               "Clear", "Prompt", "SuccessFailure", "mI=#Post", _')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 15, N'               ThisForm.Variables("RecordsPosted").Value, "@sShippingTransaction", _')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 16, N'               "", "", "", "", "", "", "", "", "", "", "", "", "", "")')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 17, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 18, N'            ''After prompting set the Records Posted variable back to 0')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 19, N'            ThisForm.Variables("RecordsPosted").Value = "0"')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 20, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 21, N'        End Sub')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 22, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 23, N'        Function CheckSelected() As Integer')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 24, N'            Dim oPrimaryCache As IWSIDOCollection')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 25, N'            Dim i As Integer')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 26, N'            Dim tot As Integer')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 27, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 28, N'            CheckSelected = 0')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 29, N'            tot = 0')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 30, N'            oPrimaryCache = ThisForm.PrimaryIDOCollection')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 31, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 32, N'            For i = 0 To ThisForm.PrimaryIDOCollection.GetNumEntries - 1')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 33, N'                If oPrimaryCache.GetObjectProperty("UbSelect", i) = "1" Then')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 34, N'                    tot = tot + 1')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 35, N'                End If')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 36, N'            Next')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 37, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 38, N'            If tot = 0 Then')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 39, N'                ThisForm.CallGlobalScript("MsgApp", "Clear", "Prompt", "SuccessFailure", "mW=NoneSelected", "@sRow", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "")')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 40, N'                CheckSelected = -1')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 41, N'                Exit Function')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 42, N'            End If')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 43, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 44, N'        End Function')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 45, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 46, N'        Sub PreShip()')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 47, N'            Dim oPrimaryCache As IWSIDOCollection')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 48, N'            Dim i As Integer')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 49, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 50, N'            oPrimaryCache = ThisForm.PrimaryIDOCollection')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 51, N'            For i = 0 To (oPrimaryCache.GetNumEntries - 1)')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 52, N'                If oPrimaryCache.GetObjectProperty("UbSelect", i) = "1" Then')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 53, N'                    oPrimaryCache.SetCurrentObject(i)')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 54, N'                    ThisForm.GenerateEvent("CallShipConfirmation")')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 55, N'                End If')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 56, N'            Next')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 57, N'            oPrimaryCache = Nothing')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 58, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 59, N'        End Sub')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 60, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 61, N'        Function VerifyOnlyInstanceAndChangeFormCaption() As Integer')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 62, N'            Dim iInstances As Integer')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 63, N'            Dim oForm As IWSForm')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 64, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 65, N'            VerifyOnlyInstanceAndChangeFormCaption = 0')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 66, N'            '' Only one instance of this form at a time may be run (due to work table usage)')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 67, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 68, N'            iInstances = 0')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 69, N'            For Each oForm In Application.Forms.Values')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 70, N'                If oForm.Name = ThisForm.Name Then')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 71, N'                    iInstances = iInstances + 1')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 72, N'                End If')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 73, N'            Next oForm')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 74, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 75, N'            If (iInstances > 1) Then')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 76, N'                '' put up the message this way, otherwise, even with PostEvent, bad things happen if')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 77, N'                '' the event handler error message puts the message up')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 78, N'                Application.ShowMessage(Application.GetStringValue("mYouMayOnlyRunOneInstanceOfThisForm"))')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 79, N'                VerifyOnlyInstanceAndChangeFormCaption = -1')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 80, N'                ThisForm.PostEvent("StdFormClose")')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 81, N'                Exit Function')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 82, N'            End If')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 83, N'            ''Update FormCurWhse if returning from ChangeWhse')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 84, N'            ThisForm.Variables("FormCurWhse").Value = Application.Variables("CurWhse").Value')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 85, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 86, N'        End Function')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 87, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 88, N'        Function StdFormCalledFormReturned() As Integer')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 89, N'            On Error GoTo ErrorHandler')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 90, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 91, N'            StdFormCalledFormReturned = 0')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 92, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 93, N'            If ThisForm.LastModalChildEndedOk = True Then')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 94, N'                ''if the user hit cancel on the modal form,')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 95, N'                ''there is no need to continue.')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 96, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 97, N'                Select Case ThisForm.LastModalChildName')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 98, N'                    Case "ChangeWarehouse"')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 99, N'                        ThisForm.GenerateEvent("ChangeWarehouse")')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 100, N'                End Select')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 101, N'            End If')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 102, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 103, N'            Exit Function')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 104, N'ErrorHandler:')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 105, N'            Application.ShowMessage("StdFormCalledFormReturned:  " & Err.Description, vbCritical)')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 106, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 107, N'        End Function')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 108, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 109, N'        Sub OnHandNegativeEnablement()')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 110, N'            Dim bEnabled As Boolean')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 111, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 112, N'            If ThisForm.Variables("LocalNegFlagVar").Value = "1" Then')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 113, N'                bEnabled = True')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 114, N'            Else')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 115, N'                bEnabled = False')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 116, N'            End If')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 117, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 118, N'            ThisForm.Components("OnHandNegVarCheckBox").Enabled = bEnabled')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 119, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 120, N'            If bEnabled = False Then')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 121, N'                ThisForm.Variables("LocalNegFlagVar").Value = "0"')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 122, N'            End If')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 123, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 124, N'        End Sub')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 125, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 126, N'        Sub SelectAll()')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 127, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 128, N'            Dim i As Integer')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 129, N'            Dim oPrimaryCache As IWSIDOCollection')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 130, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 131, N'            oPrimaryCache = ThisForm.PrimaryIDOCollection')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 132, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 133, N'            For i = 0 To ThisForm.PrimaryIDOCollection.GetNumEntries - 1')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 134, N'                oPrimaryCache.SetObjectPropertyPlusModifyRefresh("UbSelect", i, "1")')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 135, N'            Next')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 136, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 137, N'            oPrimaryCache = Nothing')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 138, N'        End Sub')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 139, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 140, N'        Sub DeselectAll()')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 141, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 142, N'            Dim i As Integer')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 143, N'            Dim oPrimaryCache As IWSIDOCollection')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 144, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 145, N'            oPrimaryCache = ThisForm.PrimaryIDOCollection')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 146, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 147, N'            For i = 0 To ThisForm.PrimaryIDOCollection.GetNumEntries - 1')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 148, N'                oPrimaryCache.SetObjectPropertyPlusModifyRefresh("UbSelect", i, "0")')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 149, N'            Next')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 150, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 151, N'            oPrimaryCache = Nothing')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 152, N'        End Sub')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 153, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 154, N'        Sub ShowHideButtons()')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 155, N'            Dim RefType As String')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 156, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 157, N'            RefType = ThisForm.Components("ZwmRefType").Text')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 158, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 159, N'            If (RefType = "O") Then')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 160, N'                ThisForm.Components("ShipButton").Visible = True')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 161, N'                ThisForm.Components("ZwmShipTransferBtn").Visible = False')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 162, N'            Else')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 163, N'                ThisForm.Components("ZwmShipTransferBtn").Visible = True')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 164, N'                ThisForm.Components("ShipButton").Visible = False')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 165, N'            End If')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 166, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 167, N'        End Sub')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 168, NULL)
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 169, N'End Class')
INSERT INTO ActiveXScriptLines ([ScriptName], [ScopeType], [ScopeName], [Sequence], [CodeLine])
VALUES (N'ZWM_ShipConfirmation', 1, N'[NULL]', 170, N'End Namespace')
-------------------------------------------------------------------------------
